-- ------------------------------------------------------------------------------
-- File       : kill_session_sqlid.sql
-- Purpose    : Oracle diagnostic query/report helper: kill session sqlid.
-- Category   : diagnostics/sessions_waits
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @kill_session_sqlid.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : READ ONLY
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
select 'alter system kill session '''||sid||','||serial#||',@'||inst_id||''' immediate;' from gv$session where sql_id='&sqlid'
/