-- ------------------------------------------------------------------------------
-- File       : pg_size_pretty.sql
-- Purpose    : postgres storage helper: pg size pretty.
-- Engine     : postgres
-- Category   : storage
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : Run with the target database client: pg_size_pretty.sql
-- Parameters : tabletest
-- Risk       : READ_ONLY
-- Output     : Client, shell or script-defined output.
-- Notes      : Validate in a non-production environment before operational use.
-- Source     : internal
-- Change Log :
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
select pg_size_pretty(pg_relation_size('&tabletest'));