-- ------------------------------------------------------------------------------
-- File       : archived_log_sequence_scn.sql
-- Purpose    : Oracle Data Guard administration helper: archived log sequence scn.
-- Category   : backup_recovery/dataguard
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @archived_log_sequence_scn.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : REVIEW
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
col FIRST_CHANGE# for 99999999999999
select sequence#,FIRST_CHANGE# from v$archived_log where sequence# = &sequence;