-- ------------------------------------------------------------------------------
-- File       : current_scn.sql
-- Purpose    : Oracle administration helper: current scn.
-- Category   : utilities
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @current_scn.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : READ ONLY
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
Ver SCN Actual de la base de Datos
select timestamp_to_scn(to_timestamp(sysdate,'DD-MM-RR HH24:MI:SS')) from dual;