-- ------------------------------------------------------------------------------
-- File       : liberar_memoria_q_ya_no_se_esta_utilizando_en_sesion.sql
-- Purpose    : Oracle administration helper: liberar memoria q ya no se esta utilizando en sesion.
-- Category   : utilities
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @liberar_memoria_q_ya_no_se_esta_utilizando_en_sesion.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : READ ONLY
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
exec dbms_session.FREE_UNUSED_USER_MEMORY ;