-- ------------------------------------------------------------------------------
-- File       : tablas_segmentos_menos10%libre.sql
-- Purpose    : Oracle administration helper: tablas segmentos menos10%libre.
-- Category   : utilities
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @tablas_segmentos_menos10%libre.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : READ ONLY
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
SELECT owner, table_name, blocks, empty_blocks from DBA_TABLES where empty_blocks /(blocks + empty_blocks) < .1;