-- ------------------------------------------------------------------------------
-- File       : tempfile.sql
-- Purpose    : Oracle administration helper: tempfile.
-- Category   : utilities
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @tempfile.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : READ ONLY
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
--tempfile.sql
select name, BYTES/1024/1024/1024 GB from v$tempfile;
--alter tablespace temp add tempfile size 2G autoextend on next 500M maxsize unlimited;