-- ------------------------------------------------------------------------------
-- File       : cStandByCtl.sql
-- Purpose    : Oracle RMAN backup, restore or recovery helper: cStandByCtl.
-- Category   : backup_recovery/rman
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @cStandByCtl.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : RMAN, Oracle environment, and required backup/recovery privileges.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : REVIEW
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
ALTER DATABASE CREATE STANDBY CONTROLFILE AS 'G:\CMCopy\CONTROL01STB.CTL';
quit