--Required privileges
GRANT SELECT ANY TRANSACTION TO DMSUSER;
GRANT SELECT on V_$ARCHIVED_LOG TO DMSUSER;
GRANT SELECT on V_$LOG TO DMSUSER;
GRANT SELECT on V_$LOGFILE TO DMSUSER;
GRANT SELECT on V_$DATABASE TO DMSUSER;
GRANT SELECT on V_$THREAD TO DMSUSER;
GRANT SELECT on V_$PARAMETER TO DMSUSER;
GRANT SELECT on V_$NLS_PARAMETERS TO DMSUSER;
GRANT SELECT on V_$TIMEZONE_NAMES TO DMSUSER;
GRANT SELECT on V_$TRANSACTION TO DMSUSER;
GRANT SELECT on ALL_INDEXES TO DMSUSER;
GRANT SELECT on ALL_OBJECTS TO DMSUSER;
GRANT SELECT on DBA_OBJECTS  TO DMSUSER;
GRANT SELECT on sys.ENC$  TO DMSUSER;
GRANT SELECT on sys.OBJ$  TO DMSUSER;
GRANT SELECT ANY TABLE TO DMSUSER;
GRANT ALTER ANY TABLE TO DMSUSER;
-- Log Mining
GRANT CREATE SESSION TO DMSUSER;
GRANT EXECUTE on DBMS_LOGMNR TO DMSUSER;
GRANT SELECT on V_$LOGMNR_LOGS TO DMSUSER;
GRANT SELECT on V_$LOGMNR_CONTENTS TO DMSUSER;
GRANT LOGMINING TO DMSUSER;
-- Binary File
GRANT CREATE SESSION TO DMSUSER;
GRANT SELECT on v_$transportable_platform  TO DMSUSER;
GRANT CREATE ANY DIRECTORY  TO DMSUSER;
GRANT EXECUTE on DBMS_FILE_TRANSFER  TO DMSUSER;
GRANT EXECUTE on DBMS_FILE_GROUP TO DMSUSER;

--Configuring an AWS-managed Oracle source for AWS DMS:
--https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.Oracle.html#CHAP_Source.Oracle.Amazon-Managed.Configuration

---Check whether supplemental logging of the table-level objects
select * from ALL_LOG_GROUPS where TABLE_NAME='';
--Setup archiving
exec rdsadmin.rdsadmin_util.set_configuration('archivelog retention hours',24);
commit;

set serveroutput on
EXEC rdsadmin.rdsadmin_util.show_configuration;

