db2 catalog TCPIP node db2node remote db2-1.cdus3jhjlk3a.us-east-1.rds.amazonaws.com server 50000


db2 catalog database rdsadmin as rdsadmin at node db2node authentication server_encrypt
  
db2 catalog database db2 as db2 at node db2node authentication server_encrypt
db2 catalog database db2 as db3 at node db2node authentication server_encrypt

db2 connect to rdsadmin user admin using admin123

db2 "select * from syscat.tables"
db2 "call rdsadmin.create_database('db2')"


db2 "call rdsadmin.drop_database('db2')"


db2 connect to db2 user admin using admin123

db2 "CREATE DATABASE TESTDB1"

db2 'CREATE TABLE "DB2INST1"."RESERVATIONS"  ("PROFILE_ID" VARCHAR(15 OCTETS) NOT NULL , "RESERVATION_NUMBER" VARCHAR(30 OCTETS) NOT NULL ,                  "PICKUP_LOCATION" VARCHAR(6 OCTETS))'
db2 'ALTER TABLE "DB2INST1"."RESERVATIONS" ADD CONSTRAINT "PK_RESP" PRIMARY KEY("PROFILE_ID","RESERVATION_NUMBER") ENFORCED;'


db2 "TRUNCATE table DB2INST1.RESERVATIONS IMMEDIATE"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 0 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 300000 ) SELECT I,'123123','LGWT52' FROM T WITH UR"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 300001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 600000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 600001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 900000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 900001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 1200000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 1200001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 1600000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 1600001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 2000000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 2000001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 3000000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 3000001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 4000000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 4000001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 5000000 ) SELECT I,'123123','LGWT52' FROM T"


db2 "select count(*) from DB2INST1.RESERVATIONS"
db2 "select count(*) from DB2INST1.RESERVATIONS_CDC"


db2 connect to rdsadmin user admin using admin123
db2 "call rdsadmin.set_archive_log_retention( ?, 'DB2', '24')"
db2 connect to db2 user admin using admin123


During FL:
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 5000001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 5500000 ) SELECT I,'123123','LGWT52' FROM T"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) VALUES (5500001,'123123','LGWT52')"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) VALUES (5500002,'123123','LGWT52')"


db2 "delete from DB2INST1.RESERVATIONS where PROFILE_ID = '6';"
db2 "UPDATE DB2INST1.RESERVATIONS SET PICKUP_LOCATION='LGWT53' where PROFILE_ID='5500000';"
db2 "UPDATE DB2INST1.RESERVATIONS SET PICKUP_LOCATION='LGWT53' where PROFILE_ID='0';"
db2 "UPDATE DB2INST1.RESERVATIONS SET PICKUP_LOCATION='LGWT53' where PROFILE_ID='6';"

After FL completed:
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) VALUES (6,'123123','LGWT52')"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) VALUES (5500003,'123123','LGWT52')"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) VALUES (5500004,'123123','LGWT52')"

During CDC
db2 "delete from DB2INST1.RESERVATIONS where PROFILE_ID = '6';"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) VALUES (6,'123123','LGWT52')"
db2 "INSERT INTO DB2INST1.RESERVATIONS ( PROFILE_ID,RESERVATION_NUMBER,PICKUP_LOCATION) WITH T (I) AS  ( SELECT 6000001 FROM SYSIBM.SYSDUMMY1   UNION ALL SELECT I+1 FROM T WHERE I < 6001001 ) SELECT I,'123123','LGWT52' FROM T"


db2 'select count(*) from "awsdms_control"."awsdms_apply_exceptions"'
db2 "select error from "awsdms_control"."awsdms_apply_exceptions" where "error" like 'UPDATE%'"


select substr(title,1,19) as title, substr(year,1,4) as year from titles;

db2 "select cast(substr(name,1,24) as varchar(24)) as name, case 
    when value_flags = 'NONE' then '' else value_flags end flags, 
    cast(substr(value,1,64) as varchar(64)) as current_value 
    from table(db_get_cfg(null)) order by name asc, member asc with UR"
	
db2 "select * from (select cast(substr(name,1,24) as varchar(24)) as name, case 
    when value_flags = 'NONE' then '' else value_flags end flags, 
    cast(substr(value,1,64) as varchar(64)) as current_value 
    from table(db_get_cfg(null)) order by name asc, member asc with UR) where name='maxlocks'"
	
	
	
db2 connect to rdsadmin user admin using admin123

db2 "call rdsadmin.update_db_param(
    'DB2', 
    'maxlocks', 
    '100000000000')"
	
	
	
	db2 "call rdsadmin.update_db_param(
    'db2', 
    'locklist', 
    '10000000')"
	


db2look -d DB2 -e -t RESERVATIONS -w "admin123" -u admin

db2 "DESCRIBE INDEXES FOR TABLE DB2INST1.RESERVATIONS_CDC SHOW DETAIL"
