-- ------------------------------------------------------------------------------
-- File       : autovacuum_when_it_started.sql
-- Purpose    : postgres performance/tuning helper: autovacuum when it started.
-- Engine     : postgres
-- Category   : performance/tuning
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : Run with the target database client: autovacuum_when_it_started.sql
-- Parameters : Review script body before running.
-- Risk       : READ_ONLY
-- Output     : Client, shell or script-defined output.
-- Notes      : Validate in a non-production environment before operational use.
-- Source     : internal
-- Change Log :
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
select backend_type, state_change from pg_stat_activity where backend_type = 'autovacuum worker';
