-- ------------------------------------------------------------------------------
-- File       : pg_stat_user_indexes.sql
-- Purpose    : postgres performance/tuning helper: pg stat user indexes.
-- Engine     : postgres
-- Category   : performance/tuning
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : Run with the target database client: pg_stat_user_indexes.sql
-- Parameters : Review script body before running.
-- Risk       : READ_ONLY
-- Output     : Client, shell or script-defined output.
-- Notes      : Validate in a non-production environment before operational use.
-- Source     : internal
-- Change Log :
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
select * from pg_stat_user_indexes where relname = 'pgbench_accounts' order by idx_scan desc;