-- ------------------------------------------------------------------------------
-- File       : vacuum_table.sql
-- Purpose    : postgres performance/tuning helper: vacuum table.
-- Engine     : postgres
-- Category   : performance/tuning
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : Run with the target database client: vacuum_table.sql
-- Parameters : Review script body before running.
-- Risk       : CHANGES
-- Output     : Client, shell or script-defined output.
-- Notes      : Validate in a non-production environment before operational use.
-- Source     : internal
-- Change Log :
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
VACUUM (INDEX_CLEANUP FALSE, VERBOSE TRUE) pgbench_accounts;