-- ------------------------------------------------------------------------------
-- File       : aws_count_xml_os_files.sql
-- Purpose    : AWS/RDS/DMS Oracle administration helper: aws count xml os files.
-- Category   : cloud/aws
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @aws_count_xml_os_files.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : REVIEW
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
select count(*) num_files, round(sum(filesize)/1024/1024) mb, round(sysdate - min(mtime),4) days from table(rdsadmin.rds_file_util.listdir('ADUMP')) where type = 'file' and filename like '%.xml';
