select
apex_debug_messages.APEX_USER,
apex_debug_messages.APPLICATION_ID,
APEX_WORKSPACE_ACTIVITY_LOG.APPLICATION_NAME,
apex_debug_messages.PAGE_ID,
apex_debug_messages.MESSAGE,
apex_debug_messages.MESSAGE_TIMESTAMP,
apex_debug_messages.PAGE_VIEW_ID,
apex_debug_messages.SESSION_ID
from APEX_WORKSPACE_ACTIVITY_LOG
inner join apex_debug_messages on APEX_WORKSPACE_ACTIVITY_LOG.DEBUG_PAGE_VIEW_ID = apex_debug_messages.PAGE_VIEW_ID
and apex_debug_messages.MESSAGE_TIMESTAMP > trunc(sysdate);