
alter session set current_schema=EXT;

set timing on
set autotrace on

VARIABLE B1 VARCHAR2(128);

begin
 :B1:='d92d425a-bb0f-41ea-87fc-873fa62795ab';
end;
/


SELECT O.NRO_BANKTRADE, 'T' TIPO_OP, NULL ID_SWIFT FROM EXT.OPP_TRF T INNER JOIN EXT.OPP_OPS O ON O.COD_OPS = T.COD_OPS INNER JOIN EXT.V_IPP_SWIFT_MSG_QUEUE V ON V.SEQ = T.ID_SWIFT WHERE V.GUID = :B1 AND V.QUEUE = 'O' UNION SELECT I.NRO_OP, 'P' TIPO_OP, I.ID_SWIFT FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'I' AND GUID = :B1 UNION
SELECT TO_CHAR(I.ID_SWIFT), 'O' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'P' AND GUID = :B1 UNION SELECT TO_CHAR(I.ID_SWIFT), 'V' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT INNER JOIN EXT.OPP_OPS_VERIF O ON O.LIQ_BKT = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'I' AND GUID =
:B1 UNION SELECT TO_CHAR(I.ID_SWIFT), 'R' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'R' AND GUID = :B1 UNION SELECT TO_CHAR(I.ID_SWIFT), 'X' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'Z' AND GUID = :B1
/


SELECT /*+DRIVING_SITE(V)*/ O.NRO_BANKTRADE, 'T' TIPO_OP, NULL ID_SWIFT FROM EXT.OPP_TRF T INNER JOIN EXT.OPP_OPS O ON O.COD_OPS = T.COD_OPS INNER JOIN EXT.V_IPP_SWIFT_MSG_QUEUE V ON V.SEQ = T.ID_SWIFT WHERE V.GUID = :B1 AND V.QUEUE = 'O' UNION SELECT /*+DRIVING_SITE(V)*/  I.NRO_OP, 'P' TIPO_OP, I.ID_SWIFT FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'I' AND GUID = :B1 UNION
SELECT /*+DRIVING_SITE(V)*/ TO_CHAR(I.ID_SWIFT), 'O' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'P' AND GUID = :B1 UNION SELECT /*+DRIVING_SITE(V)*/ TO_CHAR(I.ID_SWIFT), 'V' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT INNER JOIN EXT.OPP_OPS_VERIF O ON O.LIQ_BKT = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'I' AND GUID =
:B1 UNION SELECT /*+DRIVING_SITE(V)*/ TO_CHAR(I.ID_SWIFT), 'R' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'R' AND GUID = :B1 UNION SELECT /*+DRIVING_SITE(V)*/ TO_CHAR(I.ID_SWIFT), 'X' TIPO_OP, NULL FROM EXT.SWIFT_IN I INNER JOIN EXT.V_SWIFT_MSG V ON V.SEQ = I.ID_SWIFT WHERE V.QUEUE = 'I' AND I.ESTADO = 'Z' AND GUID = :B1
/




with V as
(
)