/*Ver cantidad de extents que tiene un objeto*/


SELECT  OWNER USUARIO, SEGMENT_TYPE TIPO, SEGMENT_NAME OBJETO, EXTENTS_ACTUALES
    FROM (SELECT   OWNER,SEGMENT_TYPE, SEGMENT_NAME,
                   EXTENTS AS "EXTENTS_ACTUALES"
              FROM DBA_SEGMENTS
             WHERE OWNER IN ('GEM_ADM','SYSTEM','SYS')
          GROUP BY OWNER, SEGMENT_TYPE, SEGMENT_NAME,EXTENTS)
   WHERE EXTENTS_ACTUALES > 10
ORDER BY USUARIO, EXTENTS_ACTUALES DESC
