SPO coe_xfr_sql_profile_b470201rk883h_2766146777.log;
SET ECHO ON TERM ON LIN 2000 TRIMS ON NUMF 99999999999999999999;
REM
REM $Header: 215187.1 coe_xfr_sql_profile_b470201rk883h_2766146777.sql 11.4.1.4 2021/09/28 csierra $
REM
REM Copyright (c) 2000-2010, Oracle Corporation. All rights reserved.
REM
REM AUTHOR
REM   carlos.sierra@oracle.com
REM
REM SCRIPT
REM   coe_xfr_sql_profile_b470201rk883h_2766146777.sql
REM
REM DESCRIPTION
REM   This script is generated by coe_xfr_sql_profile.sql
REM   It contains the SQL*Plus commands to create a custom
REM   SQL Profile for SQL_ID b470201rk883h based on plan hash
REM   value 2766146777.
REM   The custom SQL Profile to be created by this script
REM   will affect plans for SQL commands with signature
REM   matching the one for SQL Text below.
REM   Review SQL Text and adjust accordingly.
REM
REM PARAMETERS
REM   None.
REM
REM EXAMPLE
REM   SQL> START coe_xfr_sql_profile_b470201rk883h_2766146777.sql;
REM
REM NOTES
REM   1. Should be run as SYSTEM or SYSDBA.
REM   2. User must have CREATE ANY SQL PROFILE privilege.
REM   3. SOURCE and TARGET systems can be the same or similar.
REM   4. To drop this custom SQL Profile after it has been created:
REM      EXEC DBMS_SQLTUNE.DROP_SQL_PROFILE('coe_b470201rk883h_2766146777');
REM   5. Be aware that using DBMS_SQLTUNE requires a license
REM      for the Oracle Tuning Pack.
REM
WHENEVER SQLERROR EXIT SQL.SQLCODE;
REM
VAR signature NUMBER;
REM
DECLARE
sql_txt CLOB;
h       SYS.SQLPROF_ATTR;
BEGIN
sql_txt := q'[
SELECT NVL(SUM(D.REAL), 0) AS REAL_PONDERADO ,NVL(SUM(D.VALOR), 0) AS REAL_VALOR ,SUM(CASE WHEN D.PRORRATEO = 'S' THEN NVL(D.REAL, 0) ELSE 0 END) AS REAL_SUMA ,SUM(CASE WHEN D.PRORRATEO = 'N' THEN NVL(D.REAL, 0) ELSE 0 END) AS REAL_PROPIO FROM OFSA40.TPVI_DETALLE D WHERE D.INDICADOR = :B4 AND D.TIPO_PREMIO = :B3 AND D.MES BETWEEN :B2 AND :B1 AND EXISTS (SELECT 1 FROM OFSA40.PEA_SUC_REGION SR WHERE SR.SUC = D.SUCURSAL) AND EXISTS (SELECT 1 FROM OFSA40.PEA_PV04_DATOS PV WHERE PV.MES = TRUNC(:B1 , 'MM') AND PV.INDIC = :B4 AND PV.FINAL = :B5 AND PV.SUC = D.SUCURSAL)
]';
h := SYS.SQLPROF_ATTR(
q'[BEGIN_OUTLINE_DATA]',
q'[BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$CC7EC59E" "PV"@"SEL$3")]',
q'[INDEX_RS_ASC(@"SEL$CC7EC59E" "PV"@"SEL$3" ("PEA_PV04_DATOS"."MES" "PEA_PV04_DATOS"."INDIC" "PEA_PV04_DATOS"."SUC"))]',
q'[USE_NL(@"SEL$CC7EC59E" "PV"@"SEL$3")]',
q'[INDEX_SS(@"SEL$CC7EC59E" "SR"@"SEL$2" ("PEA_SUC_REGION"."REGION" "PEA_SUC_REGION"."SUC"))]',
q'[USE_NL(@"SEL$CC7EC59E" "SR"@"SEL$2")]',
q'[IGNORE_OPTIM_EMBEDDED_HINTS]',
q'[OPTIMIZER_FEATURES_ENABLE('12.1.0.2')]',
q'[DB_VERSION('12.1.0.2')]',
q'[OPT_PARAM('_connect_by_use_union_all' 'false')]',
q'[ALL_ROWS]',
q'[OUTLINE_LEAF(@"SEL$CC7EC59E")]',
q'[UNNEST(@"SEL$3")]',
q'[UNNEST(@"SEL$2")]',
q'[OUTLINE(@"SEL$1")]',
q'[OUTLINE(@"SEL$3")]',
q'[OUTLINE(@"SEL$2")]',
q'[INDEX_RS_ASC(@"SEL$CC7EC59E" "D"@"SEL$1" ("TPVI_DETALLE"."INDICADOR" "TPVI_DETALLE"."TIPO_PREMIO" "TPVI_DETALLE"."MES"))]',
q'[BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$CC7EC59E" "D"@"SEL$1")]',
q'[LEADING(@"SEL$CC7EC59E" "D"@"SEL$1" "SR"@"SEL$2" "PV"@"SEL$3")]',
q'[END_OUTLINE_DATA]');
:signature := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE(sql_txt);
DBMS_SQLTUNE.IMPORT_SQL_PROFILE (
sql_text    => sql_txt,
profile     => h,
name        => 'coe_b470201rk883h_2766146777',
description => 'coe b470201rk883h 2766146777 '||:signature||'',
category    => 'DEFAULT',
validate    => TRUE,
replace     => TRUE,
force_match => TRUE);
END;
/
WHENEVER SQLERROR CONTINUE
SET ECHO OFF;
PRINT signature
PRO
PRO ... manual custom SQL Profile has been created
PRO
SET TERM ON ECHO OFF LIN 80 TRIMS OFF NUMF "";
SPO OFF;
PRO
PRO COE_XFR_SQL_PROFILE_b470201rk883h_2766146777 completed
