/*Ejemplo PARTICION POR LISTA*/

CREATE TABLE TEST
PARTITION BY LIST (PAIS)
 (PARTITION ARGENTINA VALUES ('AR'),
  PARTITION BRASIL VALUES ('BR'),
  PARTITION PERU VALUES ('PE'),
  PARTITION CHILE VALUES ('CH'),
  PARTITION BOLIVIA VALUES ('BL'))
TABLESPACE RYA_DBA AS
SELECT PAIS,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10 FROM(
SELECT LEVEL ID ,'AR' PAIS, 'test_'||LEVEL COL2, 'test_'||LEVEL COL3, 'test_'||LEVEL COL4, 'test_'||LEVEL COL5
, 'test_'||LEVEL COL6, 'test_'||LEVEL COL7, 'test_'||LEVEL COL8, 'test_'||LEVEL COL9, 'test_'||LEVEL COL10
 FROM DUAL
     CONNECT BY LEVEL <= 1000000 UNION
SELECT LEVEL ID , 'BR' PAIS, 'test_'||LEVEL COL2, 'test_'||LEVEL COL3, 'test_'||LEVEL COL4, 'test_'||LEVEL COL5
, 'test_'||LEVEL COL6, 'test_'||LEVEL COL7, 'test_'||LEVEL COL8, 'test_'||LEVEL COL9, 'test_'||LEVEL COL10
 FROM DUAL
     CONNECT BY LEVEL <= 1000000 UNION
SELECT LEVEL ID , 'PE' PAIS, 'test_'||LEVEL COL2, 'test_'||LEVEL COL3, 'test_'||LEVEL COL4, 'test_'||LEVEL COL5
, 'test_'||LEVEL COL6, 'test_'||LEVEL COL7, 'test_'||LEVEL COL8, 'test_'||LEVEL COL9, 'test_'||LEVEL COL10
 FROM DUAL
     CONNECT BY LEVEL <= 1000000 UNION
SELECT LEVEL ID , 'CH' PAIS, 'test_'||LEVEL COL2, 'test_'||LEVEL COL3, 'test_'||LEVEL COL4, 'test_'||LEVEL COL5
, 'test_'||LEVEL COL6, 'test_'||LEVEL COL7, 'test_'||LEVEL COL8, 'test_'||LEVEL COL9, 'test_'||LEVEL COL10
 FROM DUAL
     CONNECT BY LEVEL <= 1000000 UNION
SELECT LEVEL ID , 'BL' PAIS, 'test_'||LEVEL COL2, 'test_'||LEVEL COL3, 'test_'||LEVEL COL4, 'test_'||LEVEL COL5
, 'test_'||LEVEL COL6, 'test_'||LEVEL COL7, 'test_'||LEVEL COL8, 'test_'||LEVEL COL9, 'test_'||LEVEL COL10
 FROM DUAL
     CONNECT BY LEVEL <= 1000000);



/*Indice Particionado*/


CREATE INDEX SUPERUSER.INDEX_TEST ON SUPERUSER.TEST
(PAIS)
  NOLOGGING
LOCAL (  
  PARTITION ARGENTINA
    NOLOGGING
    NOCOMPRESS,  
  PARTITION BRASIL
    NOLOGGING
    NOCOMPRESS,  
  PARTITION PERU
    NOLOGGING
    NOCOMPRESS,  
  PARTITION CHILE
    NOLOGGING
    NOCOMPRESS,  
  PARTITION BOLIVIA
    NOLOGGING
    NOCOMPRESS
)
NOPARALLEL;



/*Ejemplo PARTICION X RANGO*/


CREATE TABLE TEST
PARTITION BY RANGE (NUM)
 (PARTITION TEST_1_10000 VALUES LESS THAN (10000),
  PARTITION TEST_10000_20000 VALUES LESS THAN (20000),
  PARTITION TEST_20000_30000 VALUES LESS THAN (30000),
  PARTITION TEST_30000_40000 VALUES LESS THAN (40000),
  PARTITION TEST_40000_50000 VALUES LESS THAN (50000),
  PARTITION TEST_50000_60000 VALUES LESS THAN (60000),
  PARTITION TEST_60000_70000 VALUES LESS THAN (70000),
  PARTITION TEST_70000_80000 VALUES LESS THAN (80000),
  PARTITION TEST_80000_90000 VALUES LESS THAN (90000)
  )
TABLESPACE RYA_DBA AS
SELECT NUM,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10 FROM(
SELECT LEVEL NUM ,'test_'||LEVEL COL2, 'test_'||LEVEL COL3, 'test_'||LEVEL COL4, 'test_'||LEVEL COL5
, 'test_'||LEVEL COL6, 'test_'||LEVEL COL7, 'test_'||LEVEL COL8, 'test_'||LEVEL COL9, 'test_'||LEVEL COL10
 FROM DUAL
     CONNECT BY LEVEL <= 80000);



