CREATE TEMPORARY TABLESPACE TEMP2
TEMPFILE '/oradata/orada/sdfsdf.dbf' SIZE 3072M AUTOEXTEND ON NEXT 128M MAXSIZE 4096M;

ALTER DATABASE DEFAULT TEMPORARY TABLESPACE TEMP2;

ALTER DATABASE TEMPFILE ‘+disco/BD/tempfile/datafile’ OFFLINE;

DROP TABLESPACE TEMP INCLUDING CONTENTS AND DATAFILES;