CONNECT / AS SYSDBA
SET DEFINE OFF;
CREATE ROLE PLUSTRACE NOT IDENTIFIED;

GRANT SELECT ON  SYS.V_$MYSTAT TO PLUSTRACE;
GRANT SELECT ON  SYS.V_$SESSTAT TO PLUSTRACE;
GRANT SELECT ON  SYS.V_$STATNAME TO PLUSTRACE;

GRANT PLUSTRACE TO AHS_SOP;

CONNECT AHS_SOP/AHS_SOP

@?/rdbms/admin/utlxplan.sql
