/*
Eg
CREATE TABLE TNDOMINICAN.SM_INITIAL_BAL_R COMPRESS PCTFREE 0 TABLESPACE COL_DW_DATA as ( 
SELECT *
FROM TNDOMINICAN.SM_INITIAL_BAL
AS OF TIMESTAMP TO_TIMESTAMP('17-MAY-12 08.00.00.000000'))
/
*/