SELECT   TRUNC (FIRST_TIME) "Date", TO_CHAR (FIRST_TIME, 'Dy') "Day",
         COUNT (1) "Total",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '00', 1, 0)) "h0",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '01', 1, 0)) "h1",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '02', 1, 0)) "h2",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '03', 1, 0)) "h3",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '04', 1, 0)) "h4",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '05', 1, 0)) "h5",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '06', 1, 0)) "h6",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '07', 1, 0)) "h7",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '08', 1, 0)) "h8",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '09', 1, 0)) "h9",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '10', 1, 0)) "h10",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '11', 1, 0)) "h11",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '12', 1, 0)) "h12",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '13', 1, 0)) "h13",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '14', 1, 0)) "h14",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '15', 1, 0)) "h15",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '16', 1, 0)) "h16",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '17', 1, 0)) "h17",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '18', 1, 0)) "h18",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '19', 1, 0)) "h19",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '20', 1, 0)) "h20",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '21', 1, 0)) "h21",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '22', 1, 0)) "h22",
         SUM (DECODE (TO_CHAR (FIRST_TIME, 'hh24'), '23', 1, 0)) "h23"
    FROM V$LOG_HISTORY
GROUP BY TRUNC (FIRST_TIME), TO_CHAR (FIRST_TIME, 'Dy')
ORDER BY 1;