CREATE SMALLFILE TABLESPACE "MYTBS" DATAFILE '/u01/app/oracle/oradata/dev1/mytbs01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/

