/*+++++++++Objetos para Llevar los objetos (Packages, triggers, secuencias,procedures) 
a Memoria y que queden allí.+++++++++++++++
*/


CREATE OR REPLACE VIEW SYSTEM.VS_OBJ_PINNING
(OWNER, NAME, TYPE, SHARABLE_MEM, FECHA, 
 LOADS, TYPE_OBJ)
AS 
SELECT OWNER, NAME, TYPE, SHARABLE_MEM, SYSDATE FECHA, LOADS, B."DUMMY"
     FROM V$DB_OBJECT_CACHE, SYS.DUAL B
    WHERE TYPE IN
              ('PACKAGE', 'PACKAGE BODY', 'TRIGGER', 'SEQUENCE', 'PROCEDURE')
      AND NAME NOT IN (SELECT OBJECT_NAME FROM DBA_RECYCLEBIN)              
      AND NVL (SHARABLE_MEM, 0) > 0
      AND KEPT = 'NO'
/


CREATE PUBLIC SYNONYM VS_OBJ_PINNING FOR SYSTEM.VS_OBJ_PINNING
/

CREATE TABLE SYSTEM.SHARED_POOL_KEEP_LOG
(
  FECHA   DATE,
  TIPO    VARCHAR2(20 BYTE),
  OBJETO  VARCHAR2(50 BYTE)
)
TABLESPACE PRUEBA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE PUBLIC SYNONYM SHARED_POOL_KEEP_LOG FOR SYSTEM.SHARED_POOL_KEEP_LOG;

CREATE OR REPLACE TRIGGER SYSTEM.TRG_SHARED_POOL_LOG
   BEFORE INSERT
   ON SYSTEM.SHARED_POOL_KEEP_LOG
   REFERENCING NEW AS NUEVO OLD AS VIEJO
   FOR EACH ROW
BEGIN
:NUEVO.FECHA := SYSDATE;
EXCEPTION
   WHEN OTHERS
   THEN
      RAISE;
END TRG_SHARED_POOL_LOG;
/




CREATE TABLE SYSTEM.TAB_OBJ_PINING
(
  OWNER         VARCHAR2(64 BYTE),
  NAME          VARCHAR2(1000 BYTE),
  TYPE          VARCHAR2(28 BYTE),
  SHARABLE_MEM  NUMBER,
  FECHA         DATE,
  LOADS         NUMBER,
  TYPE_OBJ      VARCHAR2(1 BYTE)
)
TABLESPACE PRUEBA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE PUBLIC SYNONYM TAB_OBJ_PINING FOR SYSTEM.TAB_OBJ_PINING;


CREATE OR REPLACE TRIGGER SYSTEM.TRG_OBJ_TYPE
   BEFORE INSERT
   ON SYSTEM.TAB_OBJ_PINING
   REFERENCING NEW AS NUEVO OLD AS VIEJO
   FOR EACH ROW
/*Referencia :
Value        Kind of Object to keep
  --        -----        ----------------------
  --          P          package/procedure/function (Default)
  --          Q          sequence
  --          R          trigger
  --          T          type
  --          JS         java source
  --          JC         java class
  --          JR         java resource
  --          JD         java shared data
  --          C          cursor */
BEGIN
   IF :NUEVO.TYPE = 'SEQUENCE'
   THEN
      :NUEVO.TYPE_OBJ := 'Q';
   END IF;

   IF :NUEVO.TYPE IN ('FUNCTION', 'PACKAGE', 'PACKAGE BODY', 'PROCEDURE')
   THEN
      :NUEVO.TYPE_OBJ := 'P';
   END IF;

   IF :NUEVO.TYPE = 'TRIGGER'
   THEN
      :NUEVO.TYPE_OBJ := 'R';
   END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      RAISE;
END TRG_OBJ_TYPE;
/



/* Procedure Principal */


CREATE OR REPLACE PROCEDURE SYS.OBJ_SHARED_POOL_KEEP
AS
   CURSOR TO_KEEP
   IS
      SELECT OWNER || '.' || NAME NAME, TYPE_OBJ
        FROM SYSTEM.TAB_OBJ_PINING;

   STR_NAME   VARCHAR2 (1000);
   STR_TYPE   VARCHAR2 (1000);
   STR_TAB    VARCHAR2 (1000);
   INS_TAB    VARCHAR2 (1000);
BEGIN
   STR_TAB := 'TRUNCATE TABLE SYSTEM.TAB_OBJ_PINING';
   INS_TAB :=
      'INSERT INTO SYSTEM.TAB_OBJ_PINING SELECT * FROM SYSTEM.VS_OBJ_PINNING';

   EXECUTE IMMEDIATE STR_TAB;

   EXECUTE IMMEDIATE INS_TAB;

   COMMIT;

   OPEN TO_KEEP;

   LOOP
      FETCH TO_KEEP
       INTO STR_NAME, STR_TYPE;

      EXIT WHEN TO_KEEP%NOTFOUND;
      STR_TYPE := SUBSTR (STR_TYPE, 1, 1);
      DBMS_SHARED_POOL.KEEP (STR_NAME, STR_TYPE);

      INSERT INTO SHARED_POOL_KEEP_LOG
                  (TIPO, OBJETO
                  )
           VALUES (STR_TYPE, STR_NAME
                  );

      COMMIT;
   END LOOP;
END;
/



