SELECT OWNER,
       DECODE (PARTITION_NAME,
               NULL, SEGMENT_NAME,
               SEGMENT_NAME || ':' || PARTITION_NAME
              ) OBJECTNAME,
       SEGMENT_TYPE OBJECTTYPE, NVL (BYTES / 1048576, 0) SIZEMB,
       NVL (INITIAL_EXTENT, 0) INITIALEXT, NVL (NEXT_EXTENT, 0) NEXTEXT,
       NVL (EXTENTS, 0) NUMEXTENTS, NVL (MAX_EXTENTS, 0) "MAXEXTENTS"
  FROM DBA_SEGMENTS
 WHERE TABLESPACE_NAME = :TABLESPACE