SELECT   OWNER, NAME, TYPE, SHARABLE_MEM / 1024 / 1024 MB, LOADS
    FROM V$DB_OBJECT_CACHE
   WHERE NAME NOT IN (SELECT OBJECT_NAME
                        FROM DBA_RECYCLEBIN)
     AND OWNER IS NOT NULL
     AND NVL (SHARABLE_MEM, 0) > 0
     AND KEPT = 'NO'
ORDER BY LOADS DESC