set pagesize 500
set linesize 120
column A.OWNER format a16
column A.OBJECT_NAME format a16


SELECT
A.OWNER,
A.OBJECT_NAME,
A.OBJECT_TYPE,
C.SID,
C.SERIAL#,
C.USERNAME
FROM DBA_OBJECTS A,
V$LOCKED_OBJECT B
,V$SESSION C
WHERE A.OBJECT_ID = B.OBJECT_ID
AND B.SESSION_ID  = C.SID
/
