/* Ejemplo */
CREATE TABLE prueba_part
PARTITION BY RANGE (created)
(PARTITION enero2008
VALUES LESS THAN (TO_DATE('01-02-2008', 'DD-MM-YYYY')) COMPRESS,
PARTITION enero2009
VALUES LESS THAN (TO_DATE('01-02-2009', 'DD-MM-YYYY')),
PARTITION mesactual VALUES LESS THAN (MAXVALUE))
AS SELECT * FROM dba_objects;