---interval:

 

create table part
  (a date)
  PARTITION BY RANGE (a)
    INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
( 
   PARTITION p2 VALUES LESS THAN (TO_DATE('1-7-2007', 'DD-MM-YYYY')),
   PARTITION p3 VALUES LESS THAN (TO_DATE('1-8-2007', 'DD-MM-YYYY'))
); 

  alter table mypart2 SET INTERVAL (NUMTOYMINTERVAL(1,'YEAR');
  
  alter table mypart2 SET INTERVAL (NUMTODSINTERVAL(10,'DAY');
  
  
  
  CREATE TABLE TDEAL_DC
   (    "ACCOUNTING_PRODUCT" VARCHAR2(50) NOT NULL ENABLE,
        "ACCRUED_INTEREST" NUMBER(18,2),
        "AMOUNT_CONTRACTS" NUMBER(22,5),
        "BACKOFFICE_DEAL_ID" VARCHAR2(25),
        "BANKING_TRADING" VARCHAR2(50),
        "BOOK" VARCHAR2(50),
        "BUY_SELL" VARCHAR2(10),
        "CAP_FLOOR" VARCHAR2(15),
        "CONTRACT_TYPE" VARCHAR2(30) NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(3) NOT NULL ENABLE,
        "CURRENCY_PAIR" VARCHAR2(6),
        "CUSTOMER_CODE" NUMBER(15,0),
        "CUSTOMER_NAME" VARCHAR2(255),
        "CUSTOMER_MASTER_PRODUCT" VARCHAR2(50),
        "CUSTOMER_INSTRUMENT" VARCHAR2(50),
        "DAILY_TOTAL_PL" NUMBER(20,4),
        "DAY_LAG" NUMBER(4,0),
        "DAY_TRADE_PL" NUMBER(20,4),
        "DEAL_ID" VARCHAR2(25) NOT NULL ENABLE,
        "DELTA_BASE" NUMBER(22,6),
        "DELTA_TERM" NUMBER(22,6),
        "DESK" VARCHAR2(50) NOT NULL ENABLE,
        "EXCHANGE_RATE_AT_INCEPTION" NUMBER(22,6),
        "FIXING_DATE" NUMBER(8,0),
        "FUTURE_VALUE" NUMBER(20,4),
        "REFERENCE_INDEX" VARCHAR2(50),
        "INSTRUMENT" VARCHAR2(50),
        "LEGAL_VEHICLE" VARCHAR2(50),
        "MASTER_PRODUCT" VARCHAR2(50),
        "MATURITY_DATE" NUMBER(8,0) NOT NULL ENABLE,
        "MTD_PL" NUMBER(20,4),
        "MTD_PL_WITH_POOL" NUMBER(20,4),
        "NOTIONAL_AMOUNT" NUMBER(22,6),
        "NOTIONAL_CURRENCY" VARCHAR2(3),
        "OPENING_PL" NUMBER(20,4),
        "ORIGINAL_CANCELLATION" NUMBER(8,0),
        "ORIGINAL_INSTRUMENT" VARCHAR2(50),
        "ORIGINAL_PRODUCT" VARCHAR2(50),
        "ORIGINAL_STATUS" VARCHAR2(1),
        "ORIGINAL_SYSTEM" VARCHAR2(15),
        "PERC_TSIR" NUMBER(6,2),
        "PREMIUM_AMOUNT" NUMBER(22,6),
        "PREMIUM_CURRENCY" VARCHAR2(3),
        "PRESENT_VALUE" NUMBER(18,2),
        "PROCESSING_DATE" NUMBER(8,0) NOT NULL ENABLE,
        "PRODUCT" VARCHAR2(50),
        "RATE" NUMBER(12,5),
        "START_DATE" NUMBER(8,0),
        "STATUS" CHAR(1) NOT NULL ENABLE,
        "STRATEGY" VARCHAR2(50),
        "STRIKE_RATE" NUMBER(11,6),
        "SYSTEM_ORIGIN" VARCHAR2(50) NOT NULL ENABLE,
        "TRADE_DATE" NUMBER(8,0),
        "TRADE_PL" NUMBER(20,4),
        "SRC_SYS_ID" VARCHAR2(50) NOT NULL ENABLE,
        "FS_PRE" NUMBER(17,4),
        "EXCHANGE_RATE_AT_REVALUATION" NUMBER(22,6),
        "NUMBER_OF_SCHEDULE" VARCHAR2(7),
        "PAYMENT_DATE" NUMBER(8,0),
        "ZCDF" NUMBER(10,9),
        "BASE_DATE" NUMBER(8,0),
        "CONTRACT_UNIT" VARCHAR2(50),
        "DEAL_PRICE" NUMBER(14,6),
        "MARKET_PRICE" NUMBER(18,6),
        "PREVIOUS_MARKET_PRICE" NUMBER(10,5),
        "NOTIONAL_TERM" NUMBER(18,2),
        "TERM_CURRENCY" VARCHAR2(3),
        "RATE_SPREAD" NUMBER(13,7),
        "CUSTOMER_ALIAS" VARCHAR2(50),
        "FIT" VARCHAR2(50),
        "BASILEIA" VARCHAR2(50),
        "FIRM_ACCOUNT" VARCHAR2(50),
        "LOCAL_EXCHANGE_RATE_AT_STTLMNT" VARCHAR2(50),
        "S2" VARCHAR2(50),
         CONSTRAINT "CKC_BUYSELL_TDEAL" CHECK (BUY_SELL IN (NULL,' ','BUY','CLIENTE','BANCO','SELL','B','S','C','L','A','3','4')) ENABLE,
         CONSTRAINT "CKC_ORIGINALSTATUS_TDEAL" CHECK (ORIGINAL_STATUS IN (NULL,'L','A','C')) ENABLE,
         CONSTRAINT "CKC_STATUS_TDEAL" CHECK (STATUS IN ('N','C','O',NULL)) ENABLE
   ) NOCOMPRESS LOGGING
   PARTITION BY RANGE (processing_date)
   SUBPARTITION BY LIST (country)
		SUBPARTITION TEMPLATE(
			SUBPARTITION subpart_br VALUES ('BR'),
			SUBPARTITION subpart_es VALUES ('ES'),
			SUBPARTITION subpart_cr VALUES ('CR')
			)
   (PARTITION partition_20100101 VALUES LESS THAN (20100102) compress,
    PARTITION partition_20100102 VALUES LESS THAN (20100103) compress);

--alter table tdeal_dc add partition partition_20100103 values less than (20100103) compress;
	
--DROP TABLE DC22057.TDEAL_DC;

  --TABLESPACE "ZENITH_DATA"
  
/*
declare
 numero number;
 begin
 numero:=dbs_partab.add_partition('DC22057','TDEAL_DC',30);
 end;
 /
 */