Ejemplo

Grants de sistema:

SELECT 'GRANT '||PRIVILEGE||' TO '||GRANTEE||' ;' FROM DBA_SYS_PRIVS WHERE GRANTEE IN ('GEM_ADM','GEM_VTA','GEMINIS')


Grants de usuario:


SELECT 'GRANT '||PRIVILEGE||' ON '||OWNER||'.'||TABLE_NAME||' TO '||GRANTEE||' ;'  FROM DBA_TAB_PRIVS WHERE GRANTEE IN ('CAJERO','GEMINIS','GEM_VTA','SUPERVISOR')


Grant execute a procedures:



SELECT 'GRANT '||PRIVILEGE||' ON '||OWNER||'.'||TABLE_NAME||' TO '||GRANTEE||' ;'  FROM DBA_TAB_PRIVS 
WHERE PRIVILEGE='EXECUTE' AND TABLE_NAME IN (SELECT PROCEDURE_NAME FROM DBA_PROCEDURES) AND OWNER !='SYS'