CREATE INDEX GEM_ADM.AFIP_ENT_FK_I ON GEM_ADM.ENT_AFIP_RETENCIONES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.AFIP_PK ON GEM_ADM.ENT_AFIP_RETENCIONES
(AFIP_NRO_CUIT, AFIP_PERIODO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ALIT_DESTINO_UK ON GEM_ADM.STK_ALIAS_ITEMS
(ALIT_DESTINO, STK_CODIGO, STK_TIPO_ITEM, EMP_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ALIT_PK ON GEM_ADM.STK_ALIAS_ITEMS
(ALIT_CODIGO, STK_CODIGO, STK_TIPO_ITEM, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ALIT_UK ON GEM_ADM.STK_ALIAS_ITEMS
(ALIT_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.AMN_PK ON GEM_ADM.M000_ACCESOS_MENU
(AMN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ANX_ITM_PK ON GEM_ADM.ACO_ANEXO_ITEMS
(CONT_CODIGO, ANX_ITM_NUMERO, EMP_CODIGO, CANX_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.AOB_PK ON GEM_ADM.M000_ACCESOS_OBJETOS
(AMN_CODIGO, AOB_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.AOE_PK ON GEM_ADM.M000_ACCESOS_OBJETOS_EJC
(AMN_CODIGO, AOB_CODIGO, AOE_FCH_EJECUCION)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.AOP_PK ON GEM_ADM.M000_ACCESOS_OBJETOS_EJC_PARAM
(AMN_CODIGO, AOB_CODIGO, AOE_FCH_EJECUCION, AOP_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.AUT_ENT_FK_I ON GEM_ADM.ENT_COMP_AUTONOMOS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.AUT_PK ON GEM_ADM.ENT_COMP_AUTONOMOS
(AUT_ANIOMES, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.BCO_PK ON GEM_ADM.CTE_BANCOS
(BCO_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.BCT_ENT_MPA_FK_I ON GEM_ADM.ENT_MEDIO_PAGOS
(BCO_CODIGO, BCS_COD_SUCURSAL, EMP_CODIGO, MON_CODIGO, BCT_TIPO_CUENTA, 
BCT_NUMERO_CUENTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.CAT_PRV_ENT_FK_I ON GEM_ADM.STK_CATALOGO_PROVS
(ENT_CODIGO, STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CAT_PRV_PK ON GEM_ADM.STK_CATALOGO_PROVS
(ENT_CODIGO, EMP_CODIGO, STK_CODIGO, STK_TIPO_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CAT_PRV_STK_FK_I ON GEM_ADM.STK_CATALOGO_PROVS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.CCA_ODE_FK_I ON GEM_ADM.GCO_CONFIRM_CARGAS
(ODE_NUMERO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CCA_PK ON GEM_ADM.GCO_CONFIRM_CARGAS
(CCA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CCLM_CTO_FK_I ON GEM_ADM.STK_CONCEPTO_COLUMNAS
(CTO_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CCLM_PK ON GEM_ADM.STK_CONCEPTO_COLUMNAS
(CLM_CODIGO, CTO_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CCPA_CPV_FK_I ON GEM_ADM.GRL_CONDICION_PAGO_CUOTAS
(CPA_CODIGO, EMP_CODIGO, VIGENTE_DESDE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.CCPA_MON_FK_I ON GEM_ADM.GRL_CONDICION_PAGO_CUOTAS
(MON_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CCPA_PK ON GEM_ADM.GRL_CONDICION_PAGO_CUOTAS
(CCPA_ITEM, VIGENTE_DESDE, EMP_CODIGO, CPA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CECO_PK ON GEM_ADM.RH_CENTROS_DE_COSTOS
(CECO_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CER_ENT_FK_I ON GEM_ADM.CTE_ENT_RUBROS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CER_PK ON GEM_ADM.CTE_ENT_RUBROS
(ENT_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CER_RUV_FK_I ON GEM_ADM.CTE_ENT_RUBROS
(EMP_CODIGO, RUV_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CG_REF_PK ON GEM_ADM.CG_REF_CODES
(RV_DOMAIN, RV_LOW_VALUE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CIU_PK ON GEM_ADM.ZIP_CIUDADES
(PAIS_CODIGO, PROV_CODIGO, CIU_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CIVA_PK ON GEM_ADM.GRL_CON_IVAS
(CIVA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CLH_PK ON GEM_ADM.M000_CLAVE_HISTORIAS
(CLH_NUMERO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CLM_PK ON GEM_ADM.STK_COLUMNAS
(CLM_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CLPAR_PK ON GEM_ADM.M000_CLAVE_PARAMETROS
(CLP_PRIMARY)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CL_ITEM_ENT_FK_I ON GEM_ADM.STK_CLIENTE_ITEMS
(ENT_CODIGO, STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CL_ITEM_PK ON GEM_ADM.STK_CLIENTE_ITEMS
(STK_TIPO_ITEM, ENT_CODIGO, EMP_CODIGO, STK_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CL_ITEM_STK_FK_I ON GEM_ADM.STK_CLIENTE_ITEMS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_ENT_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_ENT_HASTA_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(ENT_CODIGO_HASTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_PAIS_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(PAIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_PAIS_HASTA_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(PAIS_CODIGO_HASTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COB_PK ON GEM_ADM.GCO_COMI_BONIFS
(COB_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_PROV_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(PROV_CODIGO, PAIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_PROV_HASTA_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(PROV_CODIGO_HASTA, PAIS_CODIGO_HASTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_STK_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_STK_HASTA_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(STK_TIPO_ITEM_HASTA, EMP_CODIGO_VEC_HASTA, STK_CODIGO_HASTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_VEC_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(VEC_CODIGO, EMP_CODIGO_VEC)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_VEC_HASTA_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(VEC_CODIGO_HASTA, EMP_CODIGO_VEC_HASTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_ZONA_G_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(PAIS_CODIGO, PROV_CODIGO, ZONA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COB_ZONA_G_HASTA_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(ZONA_CODIGO_HASTA, PROV_CODIGO_HASTA, PAIS_CODIGO_HASTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COC_EMP_FK_I ON GEM_ADM.ENT_COND_COMERCIALES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COC_ENT_FK_I ON GEM_ADM.ENT_COND_COMERCIALES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COC_MON_FK_I ON GEM_ADM.ENT_COND_COMERCIALES
(MON_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COC_PK ON GEM_ADM.ENT_COND_COMERCIALES
(COC_NUMERO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CODP_PK ON GEM_ADM.ZIP_COD_POSTALES
(PAIS_CODIGO, PROV_CODIGO, CIU_CODIGO, CODP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COLA_PK ON GEM_ADM.M000_COLAS
(COLA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COLA_UK ON GEM_ADM.M000_COLAS
(COLA_TNSNAME)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COLA_UK2 ON GEM_ADM.M000_COLAS
(COLA_ESQUEMA)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.COL_ITEM_ITM_FK_I ON GEM_ADM.M000_COLUMNA_ITEMS
(ITM_CODIGO, SIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COL_ITEM_PK ON GEM_ADM.M000_COLUMNA_ITEMS
(COLUMNA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.COM_RQA_EN_ENT_FK_I ON GEM_ADM.COM_AGRUPACIONES_ENTIDADES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COM_RQA_EN_PK ON GEM_ADM.COM_AGRUPACIONES_ENTIDADES
(RQA_NUMERO, EMP_CODIGO, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CONT_PK ON GEM_ADM.ACO_CONTRATOS
(CONT_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CONV_PK ON GEM_ADM.M000_CONVERSIONES
(CONV_CODIGO, CONV_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.COT_EMP_FK_I ON GEM_ADM.COM_COTIZACION_COMPRAS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.COT_ENT_FK_I ON GEM_ADM.COM_COTIZACION_COMPRAS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COT_PK ON GEM_ADM.COM_COTIZACION_COMPRAS
(COT_NUMERO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.COX_PK ON GEM_ADM.M000_CONEXIONES
(COX_USUARIO, COX_AUDIT_SID)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CPA_EMP_FK_I ON GEM_ADM.GRL_CONDICION_PAGOS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CPA_PK ON GEM_ADM.GRL_CONDICION_PAGOS
(CPA_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CPL_CIVA_FK_I ON GEM_ADM.GRL_COMPROBANTE_LETRAS
(CIVA_CODIGO, EMP_CODIGO, SUB_MOD_CODIGO, TCP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CPL_PK ON GEM_ADM.GRL_COMPROBANTE_LETRAS
(EMP_CODIGO, TCP_CODIGO, SUB_MOD_CODIGO, CIVA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CPL_SCO_FK_I ON GEM_ADM.GRL_COMPROBANTE_LETRAS
(EMP_CODIGO, SUB_MOD_CODIGO, TCP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CPR_SMOD_PK ON GEM_ADM.CCP_COMPROBANTE_SMODS
(SUB_MOD_CODIGO, EMP_CODIGO, SUB_CPR_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CPR_STK_PK ON GEM_ADM.STK_COMP_STOCKS
(CPR_STK_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CPV_CPA_FK_I ON GEM_ADM.GRL_CONDICION_PAGO_VIGENCIAS
(CPA_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CPV_PK ON GEM_ADM.GRL_CONDICION_PAGO_VIGENCIAS
(CPA_CODIGO, EMP_CODIGO, VIGENTE_DESDE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CREP_PK ON GEM_ADM.M000_CONFIG_REPORTES
(CREP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.CREP_SIS_FK_I ON GEM_ADM.M000_CONFIG_REPORTES
(SIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CTA_PK ON GEM_ADM.CCP_CUENTAS
(CTA_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CTO_PK ON GEM_ADM.STK_CONCEPTOS
(CTO_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CTP_PK ON GEM_ADM.CTE_TARJETA_CUOTAS
(MCO_CODIGO, CTP_FCH_VIGENCIA, CTP_CUOTAS)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CTRL_CTA_PK ON GEM_ADM.CCP_CTRL_CUENTAS
(EMP_CODIGO, CTRL_CTA_CUENTA, CTRL_CTA_TABLA, CTRL_CTA_COLUMNA)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CTRL_SUB_PK ON GEM_ADM.CCP_CONTROL_SUBS
(CTRL_SUB_ANIOMES, EMP_CODIGO, SUB_MOD_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.CTZ_PK ON GEM_ADM.CCP_COTIZACIONES
(CTZ_FECHA, MON_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.DEL_FXN_USR_FK_I ON GEM_ADM.M000_DELEGACIONES
(USR_NOMBRE, EMP_CODIGO, FXN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.DEL_PK ON GEM_ADM.M000_DELEGACIONES
(DEL_FI, FXN_CODIGO, EMP_CODIGO, USR_NOMBRE, USR_NOMBRE_DEL, 
DEL_FF)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.DEL_USR_FK_I ON GEM_ADM.M000_DELEGACIONES
(USR_NOMBRE_DEL)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.DEP_PK ON GEM_ADM.STK_DEPOSITOS
(DEP_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.DOM_CODP_FK_I ON GEM_ADM.ENT_DOMICILIOS
(PAIS_CODIGO, PROV_CODIGO, CIU_CODIGO, CODP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.DOM_ENT_FK_I ON GEM_ADM.ENT_DOMICILIOS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.DOM_PK ON GEM_ADM.ENT_DOMICILIOS
(DOM_CODIGO, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.DOM_SUB_FK_I ON GEM_ADM.ENT_DOMICILIOS
(SUB_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ECB_BCO_FK_I ON GEM_ADM.ENT_CUENTA_BANCOS
(BCO_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ECB_ENT_FK_I ON GEM_ADM.ENT_CUENTA_BANCOS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ECB_ENT_SUB_I ON GEM_ADM.ENT_CUENTA_BANCOS
(ENT_CODIGO, SUB_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ECB_PK ON GEM_ADM.ENT_CUENTA_BANCOS
(ENT_CODIGO, ECB_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ECB_SUB_FK_I ON GEM_ADM.ENT_CUENTA_BANCOS
(ENT_CODIGO_SUB, SUB_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ECFG_PK ON GEM_ADM.M000_EXPORT_CONFIG
(ECFG_CODIGO, ECFG_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EGE_ENT_FECHA_UK ON GEM_ADM.ENT_GRUPO_ENTIDADES
(ENT_CODIGO, EGE_FECHA_RELACION)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EGE_ENT_FK_I ON GEM_ADM.ENT_GRUPO_ENTIDADES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EGE_ENT_GRUPO_FK_I ON GEM_ADM.ENT_GRUPO_ENTIDADES
(ENT_CODIGO_GRUPO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EGE_PK ON GEM_ADM.ENT_GRUPO_ENTIDADES
(ENT_CODIGO_GRUPO, ENT_CODIGO, EGE_FECHA_RELACION)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIBP_ENT_FK_I ON GEM_ADM.ENT_ENT_IB_X_PROVINCIA
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EIBP_PK ON GEM_ADM.ENT_ENT_IB_X_PROVINCIA
(ENT_CODIGO, PAIS_CODIGO, PROV_CODIGO, EIBP_FECHA_DESDE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIBP_PROV_FK_I ON GEM_ADM.ENT_ENT_IB_X_PROVINCIA
(PAIS_CODIGO, PROV_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIC_ENT_DESPACHANTE_FK_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(ENT_CODIGO_DESPACHANTE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIC_ENT_TRANSPORTISTA_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(ENT_CODIGO_TRANSPORTISTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIC_MED_TRANS_FK_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(MET_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EIC_PK ON GEM_ADM.IMP_EMBARQUES_CABECERA
(EIC_IDENTIFICADOR_EMBARQUE, EIC_TIPO_EMBARQUE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIC_PTO_FK_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(PAIS_CODIGO, PTO_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIC_PTO_PUERTO_ORIGEN_FK_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(PAIS_CODIGO_PUERTO_ORIGEN, PTO_CODIGO_PUERTO_ORIGEN)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EIC_TFL_FK_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(MET_CODIGO, TFL_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ELEG_ENT_PK_I ON GEM_ADM.ENT_LEGAL_ENTIDADES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ELEG_PK ON GEM_ADM.ENT_LEGAL_ENTIDADES
(ENT_CODIGO, ELEG_FECHA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.EMB_EMP_FK_I ON GEM_ADM.IMP_EMBARQUES_CABECERA
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EMP_IBP_PK ON GEM_ADM.CCP_EMP_IB_X_PROVINCIA
(EMP_CODIGO, PAIS_CODIGO, PROV_CODIGO, EMIB_FECHA_DESDE)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EMP_PK ON GEM_ADM.CCP_EMPRESAS
(EMP_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENTC_ENT_FK_I ON GEM_ADM.ENT_ENT_CLASIFICACIONES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ENTC_PK ON GEM_ADM.ENT_ENT_CLASIFICACIONES
(CLAD_CODIGO, CLA_CODIGO, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ENTT_PK ON GEM_ADM.ENT_ENT_TIPOS
(ENT_CODIGO, TIPO_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENTT_TIPO_FK_I ON GEM_ADM.ENT_ENT_TIPOS
(TIPO_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_CIVA_FK_I ON GEM_ADM.ENT_ENTIDADES
(CIVA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ENT_CLA_UNI ON GEM_ADM.ENT_ENT_CLASIFICACIONES
(CLA_CODIGO, ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_CUIT_I ON GEM_ADM.ENT_ENTIDADES
(ENT_CUIT)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_CUIT_INT_I ON GEM_ADM.ENT_ENTIDADES
(ENT_CUIT_INTERNO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_DOC_I ON GEM_ADM.ENT_ENTIDADES
(ENT_NRO_DOCUMENTO, ENT_TIPO_DOCUMENTO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_ENT_MPA_FK_I ON GEM_ADM.ENT_MEDIO_PAGOS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_HLD_FK_I ON GEM_ADM.ENT_ENTIDADES
(HLD_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ENT_MPA_PK ON GEM_ADM.ENT_MEDIO_PAGOS
(ENT_CODIGO, ENT_MPA_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_NOV_EMP_FK_I ON GEM_ADM.ENT_NOVEDADES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_NOV_ENT_FK_I ON GEM_ADM.ENT_NOVEDADES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_NOV_STN_FK_I ON GEM_ADM.ENT_NOVEDADES
(STN_CODIGO, TNO_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_NOV_SUBCTA_FK_I ON GEM_ADM.ENT_NOVEDADES
(SUB_CODIGO, ENT_CODIGO_SUBCUENTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ENT_PK ON GEM_ADM.ENT_ENTIDADES
(ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_PROV_FK_I ON GEM_ADM.ENT_ENTIDADES
(PAIS_CODIGO, PROV_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_RGAN_FK_I ON GEM_ADM.ENT_ENTIDADES
(RGAN_CODIGO, RGAN_SECUENCIA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_RIVA_FK_I ON GEM_ADM.ENT_ENTIDADES
(RIVA_CODIGO, RIVA_SECUENCIA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_TRA_ENT_FK_I ON GEM_ADM.GCO_ENT_TRANSPORTISTAS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ENT_TRA_PK ON GEM_ADM.GCO_ENT_TRANSPORTISTAS
(TRA_CODIGO, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ENT_TRA_TRA_FK_I ON GEM_ADM.GCO_ENT_TRANSPORTISTAS
(TRA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EPAR_PK ON GEM_ADM.M000_EXPORT_PARAMETROS
(ECFG_CODIGO, ECFG_NOMBRE, EPAR_NOMBRE, EPAR_ORDEN)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ERR_PK ON GEM_ADM.M000_ERRORES
(ERR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ETJ_PK ON GEM_ADM.CTE_ENTIDAD_TARJETAS
(EMP_CODIGO, MCO_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EVC_PK ON GEM_ADM.ENT_VEND_COBS
(ENT_CODIGO, EMP_CODIGO, VEC_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.EVC_VEC_FK_I ON GEM_ADM.ENT_VEND_COBS
(VEC_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EXC_ITM_PK ON GEM_ADM.CCP_EXCLUSION_ITEMS
(EXC_ITM_ITEM, EMP_CODIGO, EXC_NUMERO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EXC_PK ON GEM_ADM.CCP_EXCLUSIONES
(EXC_NUMERO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EXEN_ENT_FK_I ON GEM_ADM.ENT_EXENCIONES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.EXEN_IMP_FK_I ON GEM_ADM.ENT_EXENCIONES
(IMP_CODIGO_IMPUESTO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.EXEN_PK ON GEM_ADM.ENT_EXENCIONES
(ENT_CODIGO, IMP_CODIGO_IMPUESTO, EXEN_FECHA_DESDE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.FAC_REC_IT_ITMFAC_FK_I ON GEM_ADM.COM_FAC_RECEPCION_ITEMS
(DAT_NUMERO, ITMFAC_ITEM_NUMERO, REC_ITM_ITEM_NUMERO, EMP_CODIGO, REC_NUMERO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.FAC_REC_IT_PK ON GEM_ADM.COM_FAC_RECEPCION_ITEMS
(DAT_NUMERO, ITMFAC_ITEM_NUMERO, REC_ITM_ITEM_NUMERO, REC_NUMERO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.FAC_REC_IT_REC_IT_FK_I ON GEM_ADM.COM_FAC_RECEPCION_ITEMS
(REC_ITM_ITEM_NUMERO, EMP_CODIGO, REC_NUMERO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.FXN_GRP_FXN_FK_I ON GEM_ADM.M000_FUNCION_GRUPOS
(FXN_CODIGO, GRP_NOMBRE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.FXN_GRP_GRP_FK_I ON GEM_ADM.M000_FUNCION_GRUPOS
(GRP_NOMBRE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.FXN_GRP_PK ON GEM_ADM.M000_FUNCION_GRUPOS
(GRP_NOMBRE, FXN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.FXN_ITM_ITM_FK_I ON GEM_ADM.M000_FUNCION_ITEMS
(ITM_CODIGO, SIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.FXN_ITM_PK ON GEM_ADM.M000_FUNCION_ITEMS
(FXN_CODIGO, ITM_CODIGO, SIS_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.FXN_PK ON GEM_ADM.M000_FUNCIONES
(FXN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GCO_CCB_FK_I ON GEM_ADM.GCO_COMI_BONIFS
(EMP_CODIGO_CCB, CCB_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR1_EMP_FK_I ON GEM_ADM.CCP_GRUPOS1
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR1_PK ON GEM_ADM.CCP_GRUPOS1
(GR1_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR1_RAN_FK_I ON GEM_ADM.CCP_GRUPOS1
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR2_EMP_FK_I ON GEM_ADM.CCP_GRUPOS2
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR2_PK ON GEM_ADM.CCP_GRUPOS2
(GR2_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR2_RAN_FK_I ON GEM_ADM.CCP_GRUPOS2
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR3_EMP_FK_I ON GEM_ADM.CCP_GRUPOS3
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR3_PK ON GEM_ADM.CCP_GRUPOS3
(GR3_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR3_RAN_FK_I ON GEM_ADM.CCP_GRUPOS3
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR4_EMP_FK_I ON GEM_ADM.CCP_GRUPOS4
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR4_PK ON GEM_ADM.CCP_GRUPOS4
(GR4_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR4_RAN_FK_I ON GEM_ADM.CCP_GRUPOS4
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR5_EMP_FK_I ON GEM_ADM.CCP_GRUPOS5
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR5_PK ON GEM_ADM.CCP_GRUPOS5
(GR5_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR5_RAN_FK_I ON GEM_ADM.CCP_GRUPOS5
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR6_EMP_FK_I ON GEM_ADM.CCP_GRUPOS6
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR6_PK ON GEM_ADM.CCP_GRUPOS6
(GR6_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR6_RAN_FK_I ON GEM_ADM.CCP_GRUPOS6
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR7_EMP_FK_I ON GEM_ADM.CCP_GRUPOS7
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR7_PK ON GEM_ADM.CCP_GRUPOS7
(GR7_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR7_RAN_FK_I ON GEM_ADM.CCP_GRUPOS7
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR8_EMP_FK_I ON GEM_ADM.CCP_GRUPOS8
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR8_PK ON GEM_ADM.CCP_GRUPOS8
(GR8_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR8_RAN_FK_I ON GEM_ADM.CCP_GRUPOS8
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR9_EMP_FK_I ON GEM_ADM.CCP_GRUPOS9
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GR9_PK ON GEM_ADM.CCP_GRUPOS9
(GR9_CODIGO, RAN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.GR9_RAN_FK_I ON GEM_ADM.CCP_GRUPOS9
(RAN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRL_BIT_PK ON GEM_ADM.GRL_BITACORA
(BIT_NUMERO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRL_CAI_PK ON GEM_ADM.GRL_AUTORIZACION_IMPRESION
(EMP_CODIGO, SUB_MOD_CODIGO, TCP_CODIGO, CPL_LETRA, CAI_SUC_NUMERO, 
CAI_CODIGO, CAI_FECHA_SOLIC)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRL_COR_PK ON GEM_ADM.GRL_CORREOS
(GRL_COR_CLAVE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRL_IDT_UK ON GEM_ADM.GRL_IDIOMA_TRADUCCIONES
(LNG_IDIOMA, EMP_CODIGO, STK_TIPO_ITEM, STK_CODIGO, IDT_CLAVE)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRL_LIN_PK ON GEM_ADM.GRL_LINEA_CORREOS
(GRL_COR_CLAVE, GRL_LIN_NUMERO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRP_PK ON GEM_ADM.M000_GRUPOS
(GRP_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.GRRE_PK ON GEM_ADM.M000_GRUPO_REPORTES
(GRRE_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.IB_PROV_PK ON GEM_ADM.ENT_IB_PROVS
(PAIS_CODIGO, PROV_CODIGO, IBP_CATEGORIA, CIVA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.IB_PROV_PROV_FK_I ON GEM_ADM.ENT_IB_PROVS
(PAIS_CODIGO, PROV_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ICFP_PK ON GEM_ADM.M000_IMP_CONFIG_PROCESOS
(ICFP_TIPO_CONFIG)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.IIM_PK ON GEM_ADM.STK_ITEM_IMPUESTOS
(EMP_CODIGO, STK_TIPO_ITEM, STK_CODIGO, TTA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.IMCO_PK ON GEM_ADM.M000_IMPRESORAS_COLAS
(COLA_CODIGO, IMPR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.IMPR_PK ON GEM_ADM.M000_IMPRESORAS
(IMPR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.IMP_PK ON GEM_ADM.CTE_IMPUESTOS
(IMP_CODIGO_IMPUESTO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITI_STK_FK_I ON GEM_ADM.STK_ITEM_IMPUESTOS
(EMP_CODIGO, STK_CODIGO, STK_TIPO_ITEM)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITI_TTA_FK_I ON GEM_ADM.STK_ITEM_IMPUESTOS
(TTA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITM_COM_ITM_FK_I ON GEM_ADM.M000_ITEM_COMANDOS
(ITM_CODIGO, SIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITM_COM_IXC_FK_II ON GEM_ADM.M000_ITEM_COMANDOS
(SIS_CODIGO, IXC_COMANDO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ITM_COM_PK ON GEM_ADM.M000_ITEM_COMANDOS
(IXC_ORDEN, SIS_CODIGO, ITM_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITM_CTA_TIP_CTA_I ON GEM_ADM.STK_ITEM_CUENTAS
(EMP_CODIGO, TIPO_CUENTA)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITM_ITM_ITM_FK_I ON GEM_ADM.M000_ITEM_ITEMS
(ITM_CODIGO, SIS_CODIGO, ITM_CODIGO_DEPENDE, SIS_CODIGO_DEPENDE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITM_ITM_ITM_PERTENECE_DEP_FK_I ON GEM_ADM.M000_ITEM_ITEMS
(ITM_CODIGO_DEPENDE, SIS_CODIGO_DEPENDE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ITM_ITM_PK ON GEM_ADM.M000_ITEM_ITEMS
(SIS_CODIGO, ITM_CODIGO, ITM_CODIGO_DEPENDE, SIS_CODIGO_DEPENDE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ITM_PK ON GEM_ADM.M000_ITEMS
(ITM_CODIGO, SIS_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.ITM_SIS_FK_I ON GEM_ADM.M000_ITEMS
(SIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.IVAT_CIVA_COMP_FK_I ON GEM_ADM.GRL_CON_IMP_TASAS
(CIVA_CODIGO_COMPRADOR)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.IVAT_CIVA_VEND_FK_I ON GEM_ADM.GRL_CON_IMP_TASAS
(CIVA_CODIGO_VENDEDOR)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.IVAT_TIM_FK_I ON GEM_ADM.GRL_CON_IMP_TASAS
(TIM_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


-- Note: Index I_SNAP$_CTE_IMPUESTO_CUENT will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_CTE_IMPUESTO_CUENT ON GEM_ADM.CTE_IMPUESTO_CUENTAS
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_GRL_AUTORIZACION_I will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_GRL_AUTORIZACION_I ON GEM_ADM.GRL_AUTORIZACION_IMP_BCK
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_GRL_CON_IMP_TASAS will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_GRL_CON_IMP_TASAS ON GEM_ADM.GRL_CON_IMP_TASAS
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_GRL_CON_IVA_TASAS_ will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_GRL_CON_IVA_TASAS_ ON GEM_ADM.GRL_CON_IVA_TASAS_BORRAR
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_GRL_IDIOMA_TRADUCC will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_GRL_IDIOMA_TRADUCC ON GEM_ADM.GRL_IDIOMA_TRADUCCIONES
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_GRL_NUMBER_TO_WORD will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_GRL_NUMBER_TO_WORD ON GEM_ADM.GRL_NUMBER_TO_WORD
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_M000_AYUDA_HELP will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_M000_AYUDA_HELP ON GEM_ADM.M000_AYUDA_HELP
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_M000_AYUDA_HLP will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_M000_AYUDA_HLP ON GEM_ADM.M000_AYUDA_HLP
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_M000_HELP will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_M000_HELP ON GEM_ADM.M000_HELP
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_M000_PARAM_PROCESO will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_M000_PARAM_PROCESO ON GEM_ADM.M000_PARAM_PROCESOS
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_M000_PARAM_PROCESO1 will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX GEM_ADM.I_SNAP$_M000_PARAM_PROCESO1 ON GEM_ADM.M000_PARAM_PROCESOS_BK
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


-- Note: Index I_SNAP$_M000_SISTEMAS will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE INDEX GEM_ADM.I_SNAP$_M000_SISTEMAS ON GEM_ADM.M000_SISTEMAS
(M_ROW$$)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENS_EJUD_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENT_SUBCUENTAS
(EJUD_ESTADO_JUDICIAL, EJUD_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENS_EMP_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENT_SUBCUENTAS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENS_ENT_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENT_SUBCUENTAS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.JENS_PK ON GEM_ADM.ENT_ESTADO_JUD_ENT_SUBCUENTAS
(JENS_CODIGO, ENT_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENS_SUB_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENT_SUBCUENTAS
(ENT_CODIGO_SUB, SUB_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENT_EJUD_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENTIDADES
(EJUD_CODIGO, EJUD_ESTADO_JUDICIAL)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENT_EMP_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENTIDADES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.JENT_ENT_FEC_UK_I ON GEM_ADM.ENT_ESTADO_JUD_ENTIDADES
(ENT_CODIGO, JENT_FECHA, EJUD_ESTADO_JUDICIAL, EJUD_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.JENT_ENT_FK_I ON GEM_ADM.ENT_ESTADO_JUD_ENTIDADES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.JENT_PK ON GEM_ADM.ENT_ESTADO_JUD_ENTIDADES
(JENT_CODIGO, ENT_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.LEY_PK ON GEM_ADM.GRL_LEYENDAS
(LEY_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.M000_BLO_PAN_FK_I ON GEM_ADM.M000_BLOQUES
(PAN_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_BLO_PK ON GEM_ADM.M000_BLOQUES
(PAN_CODIGO, BLO_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.M000_CAM_BLO_FK_I ON GEM_ADM.M000_CAMPOS
(PAN_CODIGO, BLO_NOMBRE)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_CAM_PK ON GEM_ADM.M000_CAMPOS
(PAN_CODIGO, BLO_NOMBRE, CAM_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_CBQ ON GEM_ADM.M000_CONFIG_BLOQUES
(COB_CODIGO, CBQ_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_CIT_PK ON GEM_ADM.M000_CONFIG_ITEMS
(COB_CODIGO, CBQ_CODIGO, CIT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_COB_PK ON GEM_ADM.M000_CONFIG_OBJETOS
(COB_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_FANU_PK ON GEM_ADM.M000_FERIADOS_ANUALES
(FANU_FCH_FERIADO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_ICFG_PK ON GEM_ADM.M000_IMPORT_CONFIG
(ICFG_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_ICOL_PK ON GEM_ADM.M000_IMPORT_COLUMNAS
(ICFG_NOMBRE, ICOL_NOMBRE_COLUMNA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_LNG_IDIOMAS_PK ON GEM_ADM.M000_LNG_IDIOMAS
(LNG_IDIOMA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_LNG_RECURSOS_IDIOMAS_PK ON GEM_ADM.M000_LNG_RECURSOS_IDIOMAS
(REC_CODIGO, LNG_IDIOMA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_LNG_RECURSOS_PK ON GEM_ADM.M000_LNG_RECURSOS
(REC_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_LNG_RECURSOS_UK ON GEM_ADM.M000_LNG_RECURSOS
(SIS_CODIGO, TP_CODIGO, LNG_CLAVE, LNG_OBJETO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_LNG_TIPO_CLAVE_PK ON GEM_ADM.M000_LNG_TIPO_CLAVE
(TP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.M000_PAN_ITM_FK_I ON GEM_ADM.M000_PANTALLAS
(SIS_CODIGO, ITM_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.M000_PAN_PK ON GEM_ADM.M000_PANTALLAS
(PAN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MCO_EMP_FK_I ON GEM_ADM.CTE_MEDIO_COBROS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MCO_MON_FK_I ON GEM_ADM.CTE_MEDIO_COBROS
(MON_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MCO_PK ON GEM_ADM.CTE_MEDIO_COBROS
(MCO_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MCO_TMC_FK_I ON GEM_ADM.CTE_MEDIO_COBROS
(EMP_CODIGO_TIPO_MOV_COMPR, SUB_MOD_TIPO_MOV_COMPROB, MOV_TIPO, TCP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MCO_TMP_FK_I ON GEM_ADM.CTE_MEDIO_COBROS
(TMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MCO_VW_UCTA_FK_I ON GEM_ADM.CTE_MEDIO_COBROS
(EMP_CODIGO, CTA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CBO_CPA_FK_I ON GEM_ADM.MGE_CONFIG_BOTONES
(CPA_CODIGO_PANTALLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CBO_CPR_FK_I ON GEM_ADM.MGE_CONFIG_BOTONES
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CBO_PK ON GEM_ADM.MGE_CONFIG_BOTONES
(CPR_CODIGO_PREFIJO, CBO_NOMBRE_FORM_ERP, CBO_NRO_BOTON)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CCO_CNC_FK_I ON GEM_ADM.MGE_CONFIG_CONSTRAINTS
(CCO_TABLA_AUXILIAR, CCO_CAMPO_AUXILIAR)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CCO_CPR_FK_I ON GEM_ADM.MGE_CONFIG_CONSTRAINTS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CCO_PK ON GEM_ADM.MGE_CONFIG_CONSTRAINTS
(CCO_TABLA_AUXILIAR, CCO_CAMPO_AUXILIAR, CCO_TABLA_EXTERNA, CCO_CAMPO_EXTERNO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CCP_CNC_FK_I ON GEM_ADM.MGE_CONFIG_COL_PANTALLAS
(CNT_NOMBRE_TABLA, CNC_NOMBRE_CAMPO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CCP_CPA_FK_I ON GEM_ADM.MGE_CONFIG_COL_PANTALLAS
(CPA_CODIGO_PANTALLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CCP_CTP_FK_I ON GEM_ADM.MGE_CONFIG_COL_PANTALLAS
(CPA_CODIGO_PANTALLA, CTP_NRO_TAB)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CCP_PK ON GEM_ADM.MGE_CONFIG_COL_PANTALLAS
(CPA_CODIGO_PANTALLA, CNT_NOMBRE_TABLA, CNC_NOMBRE_CAMPO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CDQ_CQU_FK_I ON GEM_ADM.MGE_CONFIG_DETALLE_QUERYS
(CQU_CODIGO_QUERY)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CDQ_PK ON GEM_ADM.MGE_CONFIG_DETALLE_QUERYS
(CQU_CODIGO_QUERY, CDQ_NRO_POSICION)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CLB_PK ON GEM_ADM.MGE_CONFIG_CTRL_LINEA_BASE
(CLB_LINEA_BASE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CLC_CDQ_FK_I ON GEM_ADM.MGE_CONFIG_LOV_COLUMNAS
(CQU_CODIGO_QUERY, CDQ_NRO_POSICION)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CLC_CNC2_FK_I ON GEM_ADM.MGE_CONFIG_LOV_COLUMNAS
(CNT_NOMBRE_TABLA, CLC_CAMPO_RETORNO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CLC_CNC_FK_I ON GEM_ADM.MGE_CONFIG_LOV_COLUMNAS
(CNT_NOMBRE_TABLA, CNC_NOMBRE_CAMPO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CLC_CPR_FK_I ON GEM_ADM.MGE_CONFIG_LOV_COLUMNAS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CLC_PK ON GEM_ADM.MGE_CONFIG_LOV_COLUMNAS
(CPR_CODIGO_PREFIJO, CQU_CODIGO_QUERY, CDQ_NRO_POSICION, CNT_NOMBRE_TABLA, CNC_NOMBRE_CAMPO, 
CLC_CAMPO_RETORNO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CNC_CNC_FK_I ON GEM_ADM.MGE_CONFIG_NOMBRE_COLUMNAS
(CNC_NOMBRE_TABLA_FK, CNC_NOMBRE_CAMPO_FK)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CNC_CNT_FK_I ON GEM_ADM.MGE_CONFIG_NOMBRE_COLUMNAS
(CNT_NOMBRE_TABLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CNC_CQU_FK_I ON GEM_ADM.MGE_CONFIG_NOMBRE_COLUMNAS
(CQU_CODIGO_QUERY)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CNC_PK ON GEM_ADM.MGE_CONFIG_NOMBRE_COLUMNAS
(CNT_NOMBRE_TABLA, CNC_NOMBRE_CAMPO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CNC_UK ON GEM_ADM.MGE_CONFIG_NOMBRE_COLUMNAS
(CNT_NOMBRE_TABLA, CNC_NOMBRE_FANTASIA)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CNC_UK_2 ON GEM_ADM.MGE_CONFIG_NOMBRE_COLUMNAS
(CNT_NOMBRE_TABLA, CNC_NRO_ORDEN)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CNT_CPR_FK_I ON GEM_ADM.MGE_CONFIG_NOMBRE_TABLAS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CNT_PK ON GEM_ADM.MGE_CONFIG_NOMBRE_TABLAS
(CNT_NOMBRE_TABLA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CNT_UK ON GEM_ADM.MGE_CONFIG_NOMBRE_TABLAS
(CPR_CODIGO_PREFIJO, CNT_NOMBRE_FANTASIA)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CON_PK ON GEM_ADM.MGE_CONDICIONALES
(CON_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CPA_CPA_FK_I ON GEM_ADM.MGE_CONFIG_PANTALLAS
(CPA_PANTALLA_DEPENDE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CPA_CPR_FK_I ON GEM_ADM.MGE_CONFIG_PANTALLAS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CPA_CTA_FK_I ON GEM_ADM.MGE_CONFIG_PANTALLAS
(CNT_NOMBRE_TABLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CPA_PK ON GEM_ADM.MGE_CONFIG_PANTALLAS
(CPA_CODIGO_PANTALLA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CPA_UK ON GEM_ADM.MGE_CONFIG_PANTALLAS
(CPA_NOMBRE_PANTALLA)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CPR_PK ON GEM_ADM.MGE_CONFIG_PREFIJOS
(CPR_CODIGO_PREFIJO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CQU_CNT_FK_I ON GEM_ADM.MGE_CONFIG_QUERYS
(CNT_NOMBRE_TABLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CQU_CPR_FK_I ON GEM_ADM.MGE_CONFIG_QUERYS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CQU_PK ON GEM_ADM.MGE_CONFIG_QUERYS
(CQU_CODIGO_QUERY)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_CTP_CPA_FK_I ON GEM_ADM.MGE_CONFIG_TAB_PANTALLAS
(CPA_CODIGO_PANTALLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CTP_PK ON GEM_ADM.MGE_CONFIG_TAB_PANTALLAS
(CPA_CODIGO_PANTALLA, CTP_NRO_TAB)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_CTP_UK ON GEM_ADM.MGE_CONFIG_TAB_PANTALLAS
(CPA_CODIGO_PANTALLA, CTP_NRO_ORDEN)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FAN_FUN_FK_I ON GEM_ADM.MGE_FUNCION_ANIDADAS
(FAN_FUN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FAN_PK ON GEM_ADM.MGE_FUNCION_ANIDADAS
(FUN_CODIGO, FAN_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FFO_PK ON GEM_ADM.MGE_FORM_FORMULAS
(FFO_FORM_ERP, FFO_AGRUPACION, FFO_ORDEN)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FOR_CPR_FK_I ON GEM_ADM.MGE_FORMULAS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FOR_PK ON GEM_ADM.MGE_FORMULAS
(FOR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FOR_TCO_FK_I ON GEM_ADM.MGE_FORMULAS
(TCO_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FOV_FOR_FK_I ON GEM_ADM.MGE_FORMULA_VARIABLES
(FOR_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FOV_PK ON GEM_ADM.MGE_FORMULA_VARIABLES
(FOR_CODIGO, VAR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FOV_VAR_FK_I ON GEM_ADM.MGE_FORMULA_VARIABLES
(VAR_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FPA_FUN_FK_I ON GEM_ADM.MGE_FUNCION_PARAMETROS
(FUN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FPA_PK ON GEM_ADM.MGE_FUNCION_PARAMETROS
(FUN_CODIGO, FPA_PARAMETRO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FUF_FOR_FK_I ON GEM_ADM.MGE_FUNCION_FORMULAS
(FOR_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FUF_FUN_FK_I ON GEM_ADM.MGE_FUNCION_FORMULAS
(FUN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FUF_PK ON GEM_ADM.MGE_FUNCION_FORMULAS
(FUN_CODIGO, FOR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FUN_CPR_FK_I ON GEM_ADM.MGE_FUNCIONES
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FUN_PK ON GEM_ADM.MGE_FUNCIONES
(FUN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FVA_FUN_FK_I ON GEM_ADM.MGE_FUNCION_VARIABLES
(FUN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_FVA_PK ON GEM_ADM.MGE_FUNCION_VARIABLES
(FUN_CODIGO, VAR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_FVA_VAR_FK_I ON GEM_ADM.MGE_FUNCION_VARIABLES
(VAR_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_GVA_CPR_FK_I ON GEM_ADM.MGE_GRUPO_VARIABLES
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_GVA_PK ON GEM_ADM.MGE_GRUPO_VARIABLES
(GVA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_PAR_CPR_FK_I ON GEM_ADM.MGE_PARAMETROS
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_PAR_PK ON GEM_ADM.MGE_PARAMETROS
(CPR_CODIGO_PREFIJO, PAR_CODIGO, PAR_FECHA_VIGENCIA_DESDE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_PVA_CNC_FK_I ON GEM_ADM.MGE_PANTALLA_VALIDACIONES
(CNT_NOMBRE_TABLA, CNC_NOMBRE_CAMPO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_PVA_CPA_FK_I ON GEM_ADM.MGE_PANTALLA_VALIDACIONES
(CPA_CODIGO_PANTALLA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_PVA_PK ON GEM_ADM.MGE_PANTALLA_VALIDACIONES
(PVA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_TCO_CPR_FK_I ON GEM_ADM.MGE_TIPO_CONDICIONES
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_TCO_PK ON GEM_ADM.MGE_TIPO_CONDICIONES
(TCO_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_VAR_CPR_FK_I ON GEM_ADM.MGE_VARIABLES
(CPR_CODIGO_PREFIJO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_VAR_GVA_FK_I ON GEM_ADM.MGE_VARIABLES
(GVA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_VAR_PK ON GEM_ADM.MGE_VARIABLES
(VAR_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MGE_VCO_PK ON GEM_ADM.MGE_VALIDACION_CONDICIONES
(PVA_CODIGO, VCO_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MGE_VCO_PVA_FK_I ON GEM_ADM.MGE_VALIDACION_CONDICIONES
(PVA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MI_ITM_PK ON GEM_ADM.M000_MI_ITEMS
(ITM_CODIGO_NUMERICO, USR_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MI_IT_IT_PK ON GEM_ADM.M000_MI_ITEM_ITEMS
(ITM_CODIGO_NUMERICO, ITM_CODIGO_NUMERICO_DEPENDE, USR_NOMBRE)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MOD_PK ON GEM_ADM.CCP_MODULOS
(MOD_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MON_PK ON GEM_ADM.CCP_MONEDAS
(MON_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MOVI_EMP2_FK_I ON GEM_ADM.CTE_TIPO_MOVIMIENTOS
(EMP_CODIGO_CTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MOVI_EMP_FK ON GEM_ADM.CTE_TIPO_MOVIMIENTOS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.MOVI_PK ON GEM_ADM.CTE_TIPO_MOVIMIENTOS
(MOV_TIPO, EMP_CODIGO, SUB_MOD_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.MOVI_SUB_MOD_FK ON GEM_ADM.CTE_TIPO_MOVIMIENTOS
(SUB_MOD_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MOVI_VW_UCTA2_FK_I ON GEM_ADM.CTE_TIPO_MOVIMIENTOS
(CTA_CODIGO_DIF_CAMBIO, EMP_CODIGO_CTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.MOVI_VW_UCTA_FK_I ON GEM_ADM.CTE_TIPO_MOVIMIENTOS
(CTA_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.NOV_PK ON GEM_ADM.ENT_NOVEDADES
(NOV_CODIGO, ENT_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.OPB_COB_FK_I ON GEM_ADM.GCO_OPE_BONIFS
(COB_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.OPB_OPE_ITM_FK_I ON GEM_ADM.GCO_OPE_BONIFS
(OPE_NUMERO, OPE_ITM_ITEM)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.OPB_PK ON GEM_ADM.GCO_OPE_BONIFS
(OPE_NUMERO, OPE_ITM_ITEM, COB_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PAIS_PK ON GEM_ADM.ZIP_PAISES
(PAIS_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.PAN_EMP_FK_I ON GEM_ADM.IMP_PEDIDO_ANTICIPOS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.PAN_ENT_FK_I ON GEM_ADM.IMP_PEDIDO_ANTICIPOS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PAN_PK ON GEM_ADM.IMP_PEDIDO_ANTICIPOS
(EMP_CODIGO, PAN_NUMERO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.PAN_REQEST_FK_I ON GEM_ADM.IMP_PEDIDO_ANTICIPOS
(REQEST_CODIGO, REQEST_FORMULARIO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PARIMP_PK ON GEM_ADM.CCP_PARAMETRO_IMPUTACIONES
(PAR_CODIGO, EMP_CODIGO, RAN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PAR_TIP_PK ON GEM_ADM.CCP_PARAMETRO_TIPOS
(PAR_TIP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.PAR_TIP_SIS_FK_I ON GEM_ADM.CCP_PARAMETRO_TIPOS
(SIS_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PAT_PK ON GEM_ADM.M000_PATCHES
(PAT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PFAC_PK ON GEM_ADM.CTE_PROCESO_FACTURACION
(PFAC_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PK_M000_LOVS ON GEM_ADM.M000_LOVS
(LOV_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PREG_PK ON GEM_ADM.M000_PARAM_X_REPORTES_X_GRUPO
(GRRE_CODIGO, REGR_ITEM, PREP_NOM_PARAM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.PREP_CREP_FK_I ON GEM_ADM.M000_PARAMETROS_REPORTES
(CREP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PREP_PK ON GEM_ADM.M000_PARAMETROS_REPORTES
(CREP_CODIGO, PREP_ORDEN)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PREP_UK ON GEM_ADM.M000_PARAMETROS_REPORTES
(CREP_CODIGO, PREP_NOM_PARAM)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PRE_PK ON GEM_ADM.STK_PRECIOS
(STK_CODIGO, EMP_CODIGO, STK_TIPO_ITEM, TPRE_CODIGO, PRE_F_DESDE, 
PRE_F_HASTA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.PRE_STK_FK_I ON GEM_ADM.STK_PRECIOS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO, TPRE_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.PRE_TPRE_FK_I ON GEM_ADM.STK_PRECIOS
(TPRE_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.PROV_PAIS_FK_I ON GEM_ADM.ZIP_PROVINCIAS
(PAIS_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.PROV_PK ON GEM_ADM.ZIP_PROVINCIAS
(PAIS_CODIGO, PROV_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.RAN_PK ON GEM_ADM.CCP_RANGOS
(RAN_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.REGR_PK ON GEM_ADM.M000_REPORTES_X_GRUPO
(GRRE_CODIGO, REGR_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.REL_PK ON GEM_ADM.STK_RELACIONES
(EMP_CODIGO, STK_TIPO_ITEM, STK_CODIGO, STK_CODIGO_REL)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.REL_STK_FK_I ON GEM_ADM.STK_RELACIONES
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.RIEI_ENT_FK_I ON GEM_ADM.IMP_REQ_IMPO_EXPO_ITEMS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.RIEI_PK ON GEM_ADM.IMP_REQ_IMPO_EXPO_ITEMS
(EMP_CODIGO, RIE_NUMERO, RIEI_ITEM)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.RIEI_REQEST_FK_I ON GEM_ADM.IMP_REQ_IMPO_EXPO_ITEMS
(REQEST_CODIGO, REQEST_FORMULARIO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.RIEI_RIE_FK_I ON GEM_ADM.IMP_REQ_IMPO_EXPO_ITEMS
(EMP_CODIGO, RIE_NUMERO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.RIEI_STK_FK_I ON GEM_ADM.IMP_REQ_IMPO_EXPO_ITEMS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.RIEI_UME_FK_I ON GEM_ADM.IMP_REQ_IMPO_EXPO_ITEMS
(UME_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.RUV_PK ON GEM_ADM.CTE_RUBRO_VENTAS
(RUV_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.SCO_CPR_FK_I ON GEM_ADM.CTE_SUBMOD_COMPROBANTES
(CPR_CODIGO, EMP_CODIGO_CONT_MOD)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.SCO_CPR_SMOD_FK_I ON GEM_ADM.CTE_SUBMOD_COMPROBANTES
(SUB_MOD_CODIGO_CONT, EMP_CODIGO_CONT_SMOD, SUB_CPR_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.SCO_PK ON GEM_ADM.CTE_SUBMOD_COMPROBANTES
(EMP_CODIGO, TCP_CODIGO, SUB_MOD_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.SCO_SUB_MOD_FK_I ON GEM_ADM.CTE_SUBMOD_COMPROBANTES
(SUB_MOD_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.SCO_TCP_FK_I ON GEM_ADM.CTE_SUBMOD_COMPROBANTES
(TCP_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_CLR_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(CLR_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_CPD_CONTIENE_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(CPD_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_CTA_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(EMP_CODIGO, CTA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.STK_CTA_PK ON GEM_ADM.STK_ITEM_CUENTAS
(TIPO_CUENTA, RAN_CODIGO, EMP_CODIGO, STK_TIPO_ITEM, STK_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_CTA_RAN_FK_I ON GEM_ADM.STK_ITEM_CUENTAS
(RAN_CODIGO)
LOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_EMP_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_ESTK_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(ESTK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.STK_ITEM_UK ON GEM_ADM.STK_ITEM_STOCKS
(EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_MCA_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(MCA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_MON_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(MON_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.STK_PK ON GEM_ADM.STK_ITEM_STOCKS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_REP_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(REP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_SBI_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(RBI_CODIGO, SBI_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.STK_TIP_CTA_PK ON GEM_ADM.STK_TIPO_CUENTAS
(EMP_CODIGO, TIPO_CUENTA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_TST_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(TST_CODIGO, EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_UME_CONTIENE_FACT_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(UME_CODIGO_CONTIENE_FACT)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_UME_CONTIENE_ST_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(UME_CODIGO_CONTIENE_ST)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.STK_UME_FK_I ON GEM_ADM.STK_ITEM_STOCKS
(UME_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.STV_PK ON GEM_ADM.STK_SUB_TIPO_VALORES
(STK_CODIGO, STV_VALOR_STIP, STIP_CODIGO, STK_TIPO_ITEM, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.SUB_ENT_FK_I ON GEM_ADM.ENT_SUBCUENTAS
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.SUB_MOD_MOD_FK_I ON GEM_ADM.CCP_SUBMODULOS
(MOD_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.SUB_MOD_PK ON GEM_ADM.CCP_SUBMODULOS
(SUB_MOD_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.SUB_PK ON GEM_ADM.ENT_SUBCUENTAS
(SUB_CODIGO, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TBC_PK ON GEM_ADM.M000_TABLA_COLUMNAS
(TBL_TABLA, TBC_COLUMNA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TBL_PK ON GEM_ADM.M000_TABLAS
(TBL_TABLA)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCN_CTA1_FK_I ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(CTA_CODIGO_1, EMP_CODIGO_1)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCN_CTA2_FK_I ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(CTA_CODIGO_2, EMP_CODIGO_2)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCN_EMP_FK_I ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCN_ENT1_FK_I ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(ENT_CODIGO_1)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCN_ENT2_FK_I ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(ENT_CODIGO_2)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCN_MON_FK_I ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(MON_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TCN_PK ON GEM_ADM.CNC_TIPO_CONCILIACIONES
(TCN_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.TCP_EMP_FK_I ON GEM_ADM.CTE_TIPO_COMPROBANTES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TCP_PK ON GEM_ADM.CTE_TIPO_COMPROBANTES
(EMP_CODIGO, TCP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TDEP_PK ON GEM_ADM.STK_TIPO_DEPOSITOS
(TDEP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TIM_PK ON GEM_ADM.GRL_TIPO_IMPUESTOS
(TIM_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TIPO_PK ON GEM_ADM.ENT_TIPOS_ENTIDADES
(TIPO_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TOE_PK ON GEM_ADM.TCO_OPE_ENT
(ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TPRE_PK ON GEM_ADM.STK_TIPO_PRECIOS
(TPRE_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TRA_PK ON GEM_ADM.GCO_TRANSPORTISTAS
(TRA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.TST_EMP_FK_I ON GEM_ADM.STK_TIPO_STOCKS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TST_PK ON GEM_ADM.STK_TIPO_STOCKS
(TST_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TTA_PK ON GEM_ADM.GRL_TIPO_TASAS
(TTA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.TTI_IMP_FK_I ON GEM_ADM.GRL_TIPO_TASA_IMPUESTOS
(IMP_CODIGO_IMPUESTO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.TTI_PK ON GEM_ADM.GRL_TIPO_TASA_IMPUESTOS
(SUB_SIGNO_SUBMODULO, TTA_CODIGO, TIM_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.TTI_TIM_FK_I ON GEM_ADM.GRL_TIPO_TASA_IMPUESTOS
(TIM_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.TTI_TTA_FK_I ON GEM_ADM.GRL_TIPO_TASA_IMPUESTOS
(TTA_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.UCP_ENT_FK_I ON GEM_ADM.STK_ULTIMA_COMPS
(ENT_CODIGO, STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.UCP_PK ON GEM_ADM.STK_ULTIMA_COMPS
(EMP_CODIGO, STK_CODIGO, STK_TIPO_ITEM, ENT_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.UCP_STK_FK_I ON GEM_ADM.STK_ULTIMA_COMPS
(STK_TIPO_ITEM, EMP_CODIGO, STK_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.UME_PK ON GEM_ADM.STK_UNID_MEDIDAS
(UME_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.USR_CTA_EMP_FK_I ON GEM_ADM.CCP_USUARIO_CUENTAS
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.USR_CTA_PK ON GEM_ADM.CCP_USUARIO_CUENTAS
(USR_NOMBRE, CTA_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.USR_CTA_USR_FK_I ON GEM_ADM.CCP_USUARIO_CUENTAS
(USR_NOMBRE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.USR_GRP_EMP_FK_I ON GEM_ADM.M000_USUARIO_GRUPOS
(EMP_CODIGO, GRP_NOMBRE, USR_NOMBRE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.USR_GRP_GRP_FK_I ON GEM_ADM.M000_USUARIO_GRUPOS
(GRP_NOMBRE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.USR_GRP_PK ON GEM_ADM.M000_USUARIO_GRUPOS
(GRP_NOMBRE, USR_NOMBRE, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.USR_GRP_USR_FK_I ON GEM_ADM.M000_USUARIO_GRUPOS
(USR_NOMBRE)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.VAL_EMP_FK_I ON GEM_ADM.CCP_VALES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.VAL_PK ON GEM_ADM.CCP_VALES
(VAL_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.VEC_EMP_FK_I ON GEM_ADM.CTE_VENDEDOR_COBRADORES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.VEC_PK ON GEM_ADM.CTE_VENDEDOR_COBRADORES
(VEC_CODIGO, EMP_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.VSE_NOV_EMP_FK_I ON GEM_ADM.VSE_NOVEDADES
(EMP_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.VSE_NOV_ENT_FK_I ON GEM_ADM.VSE_NOVEDADES
(ENT_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.VSE_NOV_PK ON GEM_ADM.VSE_NOVEDADES
(EMP_CODIGO, ENT_CODIGO, NOV_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


CREATE INDEX GEM_ADM.VSE_NOV_STN_FK_I ON GEM_ADM.VSE_NOVEDADES
(TNO_CODIGO, STN_CODIGO)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE INDEX GEM_ADM.VSE_NOV_SUCUENTA_FK_I ON GEM_ADM.VSE_NOVEDADES
(SUB_CODIGO, ENT_CODIGO_SUBCUENTA)
LOGGING
TABLESPACE GEMIDXS
NOPARALLEL;


CREATE UNIQUE INDEX GEM_ADM.ZONA_G_PK ON GEM_ADM.ZIP_ZONA_GEOGRAFICAS
(PAIS_CODIGO, PROV_CODIGO, ZONA_CODIGO)
NOLOGGING
TABLESPACE GEMDATS
NOPARALLEL;


