DROP INDEX GEM_TV.AVI_CINV_FK_I;
    CREATE INDEX GEM_TV.AVI_CINV_FK_I ON GEM_TV.PUP_AVISOS
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.AVI_ORD_ITE_FK_I;
    CREATE INDEX GEM_TV.AVI_ORD_ITE_FK_I ON GEM_TV.PUP_AVISOS
    (EMP_CODIGO,ORD_NUMERO,AVI_ITEM) TABLESPACE GEMIDXSS ;    
    
    
DROP INDEX GEM_TV.AVM_CINV_FK_I;
    CREATE INDEX GEM_TV.AVM_CINV_FK_I ON GEM_TV.PUP_AVISOS_MOVIMIENTOS
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;    
    
DROP INDEX GEM_TV.AVM_PRO_FK_I;
    CREATE INDEX GEM_TV.AVM_PRO_FK_I ON GEM_TV.PUP_AVISOS_MOVIMIENTOS
    (EMP_CODIGO,SEN_CODIGO,PRO_FECHA) TABLESPACE GEMIDXSS ;    


DROP INDEX GEM_TV.CINV_SEN_CANJE_FK_I;
    CREATE INDEX GEM_TV.CINV_SEN_CANJE_FK_I ON GEM_TV.PUP_CON_INVERSION
    (EMP_CODIGO,SEN_CODIGO_CANJE) TABLESPACE GEMIDXSS ;
    

DROP INDEX GEM_TV.CICU_CINV_FK_I;
    CREATE INDEX GEM_TV.CICU_CINV_FK_I ON GEM_TV.PUP_CON_INVERSION_CUOTAS
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;        
    
DROP INDEX GEM_TV.MEME_TIIC_FK_I;
    CREATE INDEX GEM_TV.MEME_TIIC_FK_I ON GEM_TV.PUP_METAS_MENSUALES
    (EMP_CODIGO,TIIC_CODIGO) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.ORD_CINV_FK_I;
    CREATE INDEX GEM_TV.ORD_CINV_FK_I ON GEM_TV.PUP_ORDENES
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;

DROP INDEX GEM_TV.ORD_TEM_FK_I;
    CREATE INDEX GEM_TV.ORD_TEM_FK_I ON GEM_TV.PUP_ORDENES
    (TEM_CODIGO,PRD_CODIGO) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.CAC_CINV_FK_I;
    CREATE INDEX GEM_TV.CAC_CINV_FK_I ON GEM_TV.PUP_PROVISION_AGEN_X_CONTRATO
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.RATI_SEG_FK_I;
    CREATE INDEX GEM_TV.RATI_SEG_FK_I ON GEM_TV.PUP_RATING
    (EMP_CODIGO,SEN_CODIGO,SEG_CODIGO) TABLESPACE GEMIDXSS ;
    
DROP INDEX GEM_TV.CIC_GRP_FK_I;
    CREATE INDEX GEM_TV.CIC_GRP_FK_I ON GEM_TV.PRO_CICLOS
    (EMP_CODIGO,GRP_CODIGO) TABLESPACE GEMIDXSS ;
    
DROP INDEX GEM_TV.SEME_SEG_FK_I;
    CREATE INDEX GEM_TV.SEME_SEG_FK_I ON GEM_TV.PRO_SEGMENTO_MEDIDORA
    (EMP_CODIGO,SEN_CODIGO,SEG_CODIGO) TABLESPACE GEMIDXSS ;        

DROP INDEX GEM_TV.PDD_PRO_FK_I;
    CREATE INDEX GEM_TV.PDD_PRO_FK_I ON GEM_TV.PRO_PROGRAMACION_DIA_DETALLES
    (EMP_CODIGO,SEN_CODIGO,PRO_FECHA) TABLESPACE GEMIDXSS ;    

DROP INDEX GEM_TV.PDD_SEG_FK_I;
    CREATE INDEX GEM_TV.PDD_SEG_FK_I ON GEM_TV.PRO_PROGRAMACION_DIA_DETALLES
    (EMP_CODIGO_SEG,SEN_CODIGO_SEG,SEG_CODIGO) TABLESPACE GEMIDXSS ;

DROP INDEX GEM_TV.PDD_CON_FK_I;
    CREATE INDEX GEM_TV.PDD_CON_FK_I ON GEM_TV.PRO_PROGRAMACION_DIA_DETALLES
    (EMP_CODIGO,CON_NUMERO) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.ASIE_CINV_FK_I;
    CREATE INDEX GEM_TV.ASIE_CINV_FK_I ON GEM_TV.TV_ASIENTOS
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;
    
DROP INDEX GEM_TV.PRO_PAIM_CEN_FK_I;
    CREATE INDEX GEM_TV.PRO_PAIM_CEN_FK_I ON GEM_TV.TV_ASIENTOS
    (EMP_CODIGO,CON_NUMERO,CEN_CODIGO) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.PRO_PAIM_CON_FK_I;
    CREATE INDEX GEM_TV.PRO_PAIM_CON_FK_I ON GEM_TV.TV_ASIENTOS
    (EMP_CODIGO,CON_NUMERO) TABLESPACE GEMIDXSS ;

            
DROP INDEX GEM_TV.CIE_PRO_FK_I;
    CREATE INDEX GEM_TV.CIE_PRO_FK_I ON GEM_TV.PRO_PROGRAMACION_CIERRES
    (EMP_CODIGO,SEN_CODIGO,PRO_FECHA) TABLESPACE GEMIDXSS ;            


DROP INDEX GEM_TV.CIE_GRP_FK_I;
    CREATE INDEX GEM_TV.CIE_GRP_FK_I ON GEM_TV.PRO_PROGRAMACION_CIERRES
    (GRP_NOMBRE) TABLESPACE GEMIDXSS ;


DROP INDEX GEM_TV.PREF_CICU_FK_I;
    CREATE INDEX GEM_TV.PREF_CICU_FK_I ON GEM_TV.TV_PREFACTURAS
    (PUC_CODIGO,CINV_CODIGO,CICU_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;    
    
        
DROP INDEX GEM_TV.PREF_CINV_FK_I;
    CREATE INDEX GEM_TV.PREF_CINV_FK_I ON GEM_TV.TV_PREFACTURAS
    (PUC_CODIGO,CINV_CODIGO,EMP_CODIGO) TABLESPACE GEMIDXSS ;
        