--sql_id_to_signature.sql
SET SERVEROUTPUT ON
DECLARE
 SQL_TEXT   CLOB;
 SIG       NUMBER;
BEGIN
 SELECT SQL_TEXT
 INTO SQL_TEXT
 FROM DBA_HIST_SQLTEXT
 WHERE SQL_ID = '&sql_id';
 SIG := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE (SQLTEXT, FALSE);
 DBMS_OUTPUT.PUT_LINE ('SIGNATURE=' || SIG);
END;
/