SQL> select GROUP# from v$logfile where TYPE='STANDBY' group by GROUP#;

    GROUP#
----------
ALTER DATABASE CLEAR LOGFILE GROUP    3;
ALTER DATABASE CLEAR LOGFILE GROUP   11;
ALTER DATABASE CLEAR LOGFILE GROUP   12;
ALTER DATABASE CLEAR LOGFILE GROUP   14;
ALTER DATABASE CLEAR LOGFILE GROUP   15;
ALTER DATABASE CLEAR LOGFILE GROUP   16;


ALTER DATABASE CLEAR LOGFILE GROUP 3;


set pages 100

select 'ALTER DATABASE CLEAR LOGFILE GROUP '||group#||';' from v$log;