/* Tamaño Objetos de la BD en MB */

SELECT   OWNER, SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME,
         BYTES / 1024 / 1024 || ' MB' MB
    FROM DBA_SEGMENTS
   WHERE OWNER <> 'SYS'
ORDER BY BYTES DESC