-- ------------------------------------------------------------------------------
-- File       : srv.service.taf.sql
-- Purpose    : Oracle RAC or cluster administration helper: srv service taf.
-- Category   : platform/rac
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : @srv.service.taf.sql
-- Parameters : Review ACCEPT variables and substitution variables before running.
-- Requires   : SQL*Plus or SQLcl and privileges required by referenced dictionary views.
-- Oracle Ver.: Review compatibility before production use.
-- Risk       : READ ONLY
-- Output     : SQL*Plus/SQLcl console or spool output.
-- Notes      : Validate in a non-production session before operational use.
-- Source     : internal
-- Change Log : 
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
srvctl modify service -db crm -service GL -failovermethod BASIC -failovertype SELECT 
-failoverretry 10 -failoverdelay 30