-- ------------------------------------------------------------------------------
-- File       : pg_drop_replication_slot.sql
-- Purpose    : postgres replication helper: pg drop replication slot.
-- Engine     : postgres
-- Category   : replication
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : Run with the target database client: pg_drop_replication_slot.sql
-- Parameters : Review script body before running.
-- Risk       : READ_ONLY
-- Output     : Client, shell or script-defined output.
-- Notes      : Validate in a non-production environment before operational use.
-- Source     : internal
-- Change Log :
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
select pg_drop_replication_slot('slot2');
