-- ------------------------------------------------------------------------------
-- File       : pg_replication_slots_create.sql
-- Purpose    : postgres replication helper: pg replication slots create.
-- Engine     : postgres
-- Category   : replication
-- Author     : Diego Cabrera
-- Created    : Unknown
-- Version    : 1.0
-- Usage      : Run with the target database client: pg_replication_slots_create.sql
-- Parameters : Review script body before running.
-- Risk       : READ_ONLY
-- Output     : Client, shell or script-defined output.
-- Notes      : Validate in a non-production environment before operational use.
-- Source     : internal
-- Change Log :
-- 2026-05-11 : Diego Cabrera - Header normalization.
-- ------------------------------------------------------------------------------
--
--Test decoding
SELECT * FROM pg_create_logical_replication_slot('mydmssource_replication_slot', 'test_decoding');
